### ISSUE TITLE
[HTML] Obsolete or deprecated elements and attributes 

### ISSUE THREAD

**Issue by philipbordallo** [sublimehq/Packages#102]
While cleaning up the empty elements (PR #101), I noticed a lot of elements and attributes in [`html_completions.py`](https://github.com/sublimehq/Packages/blob/f7f96a0c31f6d6362dcb7ebfab6d1a0db7641f60/HTML/html_completions.py) that are deprecated/obsolete in HTML 4.01 and/or HTML 5. 

- Should these be removed?
- Is there any reason to keep them?

**Comment by kleinfreund** [comment]
I don't see a reason to *remove* them. Someone somewhere will touch old code with obsolete elements.

**Comment by philipbordallo** [comment]
I agree that backward compatibility should be kept in mind, and I'm not suggesting taking those elements out of `HTML.sublime-syntax`. 

But rather removing them out of `html_completions.py` as to prevent bad practices like using `<center>` or adding the `align` attribute to a `<div>`.

That someone somewhere having to work on older versions of HTML is most likely rarer than the person using Sublime to write valid HTML 5 markup.

**Comment by kleinfreund** [comment]
That sounds good to me. Don’t see a big reason not to remove them from the completions.

**Comment by titoBouzout** [comment]
I think we should allow and also add the missing ones, beacuse there are tons of legacy code outthere, and also could be editing non-html files where these html completation could become handy. 

If you really want HTML5, then find a way to detect `<!DOCTYPE html>` and reduce the completions in THAT situation.

My last usage of the "bad practice" of using "<center>"  was last week because I had to write an HTML email that "looks" nice in a good amount of email providers. So please dont remove stuff, make it more smart instead.

**Comment by wbond** [comment]
I don't think there is any benefit to removing completions or highlighting for deprecated elements or attributes. They are mostly there as tools to help people be more productive, but shouldn't really get in the way of others.

I think if there are any completions of standard tags that include attributes that are superfluous, we can consider removing those. For instance, there isn't the need for a completion of `<div>` to include the `align=""` attribute.

So, if you know of any areas that need attention, please open a specific issue and we can discuss further.
