### ISSUE TITLE
[batch] Trailing space on syntax text

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1097]
```batch
File: Packages\Batch File\syntax_test_batch_file.bat
441: 
442: ::                        | this is a deliberate trailing space
443: set /p today=enter a date: 
...
448: ::                         ^ - meta.prompt.set.dosbatch
```
While saving the file adding new tests, my Sublime Text trimmed the lines, and I find out this test failing if the trailing white space is removed. Any syntax tests should depend on trailing spaces, is this by design why?

![image](https://user-images.githubusercontent.com/5332158/28938095-5deb5be6-7863-11e7-8259-d0d6a382d130.png)

**Comment by keith-hall** [comment]
ST's default preferences include `"trim_automatic_white_space": true` - obviously there is no way to have syntax specific preferences for syntax tests, but you could write a plugin / update PackageDev to set `"trim_automatic_white_space": false` on the view if it is a syntax test view.

**Comment by rwols** [comment]
I think @keith-hall should be able to clarify why he wrote it like this: bff92cd3dce9 ;)
And yes, having this as a feature of PackageDev would be very nice.

**Comment by FichteFoll** [comment]
I'm opposed to setting `"trim_automatic_white_space": false` to syntax test files in PackageDev because it would be *very* annoying to me when writing test files. Remember that most content of a test file is *actual* source code that you want to test against, so it feels a lot like writing code, and I don't want to bother with having to remove trailing whitespace when doing that.

If people need trailing spaces in (any of) their files, they should take care of handling the corresponding setting themselves, imo.

**Comment by evandrocoan** [comment]
Merged on https://github.com/sublimehq/Packages/pull/1099
