### ISSUE TITLE
[Python] Differences between Builds 3083 and 3095 regarding regex highlighting

### ISSUE THREAD

**Issue by MattDMo** [sublimehq/Packages#115]
Consider the following code:
```python
reg = re.compile(r'(\s*[([]?\s*H\s*[\|/-]?\s*F\s*[)\]]?)?$', re.I)
```
Seems simple enough, a regular expression defined in a raw string literal, containing a bunch of parens and brackets and stuff. Github properly ends the string at the closing single quote `'`. However, earlier versions of Sublime's Python syntax, and my own [Python Improved](https://packagecontrol.io/packages/Python%20Improved) syntax, have had issues with finding the closing paren `)` in capture groups, and the closing string marker (single single or double quotes, or triple single or double quotes). Here's an example using the Build 3083 `.tmLanguage` definition (Python Improved looks identical):
<img width="496" alt="Build 3083 Python.tmLanguage" src="https://cloud.githubusercontent.com/assets/1776358/12151270/47340404-b47c-11e5-9b54-43d555a5353d.png">

Here is an example using Build 3095 and the new `.sublime-syntax` format:
<img width="493" alt="Build 3095 Python.sublime-syntax" src="https://cloud.githubusercontent.com/assets/1776358/12151297/6edd5122-b47c-11e5-8994-533e1a5e0135.png">

You can see how the regex scopes in the upper example are never terminated. I encourage you to play around with the sequence using the 3083 definition or Python Improved, and see what characters are required to close the regex.

I took both images using Build 3095 on OS X, but I and others have been able to replicate it with previous releases and on Windows and Ubuntu as well, so I'm pretty sure it's not a platform or build thing. I've translated both `PythonImproved.tmLanguage` and Build 3083's `Python.tmLanguage` into `sublime-syntax` format, with no luck. Since there's no backwards conversion tool, I can't translate Build 3095's `Python.sublime-syntax` into either `tmLanguage`, `YAML-tmLanguage`, or `JSON-tmLanguage` formats to see what the difference is.

I'm dreading having to go through the Python Improved and original Python `sublime-syntax` files line by line and regex by regex to see what's different (answer: a lot) *and* relevant. I'm assuming it has something to do with how quotes and/or parentheses/brackets/braces are matched, but I'm not sure. `Regular Expressions (Python).tmLanguage` has also changed to `sublime-syntax`, so I don't know.

So, I have two questions for whoever did the conversion from `tmLanguage` to `sublime-syntax`: what did you do differently to make regexes like this work? Also (slightly less important, but interesting all the same): How did you scope the content of regexes in raw string literals as `source.regexp.python` when it wasn't before?

I am ***extremely*** interested in learning the answers to those questions, especially the first. Thanks!

PS: While we're at it, a third, somewhat related question: why not expand from AAAPackageDev's `YAML-tmLanguage` instead of making your own, incompatible format? Just wondering, because I have great syntax highlighting of the regexes in `.YAML-tmLanguage` files (thanks to my [Neon Color Scheme](https://packagecontrol.io/packages/Neon%20Color%20Scheme)), but everything in `.sublime-syntax` files is just boring strings. Also, it's a format developers already know (hopefully) so there isn't as steep of a learning curve. Maybe there were just too many features you wanted to put into `sublime-syntax` that it wasn't worth it. I'm trying to adapt the `YAML-tmLanguage` syntax def to `sublime-syntax`, but that'll take a while. Anyways, thanks again!

**Comment by FichteFoll** [comment]
This is a recurring issue mentioned in a couple issues and I also iterated on it a couple times on the SublimeTextIssues org, but I'll give you a short explanation for this phenomenon along with a reason for why `.sublime-syntax` is better.

The underlying issue for this problem is (following `.sublime-syntax` terminology) "nested contexts" and the inclusion of other syntaxes via `tmLanguage`'s "include". Regular expressions in Python as well as a SQL queries are highlighted in Python in strings, if certain conditions are met. The conditions aside, these highlightings are done using includes.

Includes require begin-end patterns to encapsulate the include inside a region and allow things like escape sequences because any matched character can not be matched again, even by an end pattern. Thus, you can imagine the end pattern of a begin-end pattern just like a normal pattern inside the region that will terminate the begin-end pattern (or "context") if it matches. By default, this end pattern match is inserted at the beginning of the sub-patterns but it can be moved to the end by setting `applyEndPatternLast` to `1`. For that reason, `.sublime-syntax` is **perfectly backwards compatible**.

Now, probles arise if the included patterns (i.e. the regex syntax) includes begin-end patterns itself and thus creates nested patterns. In `.tmLanguage`, the end pattern of the including match can not match anything that is consumed by a begin-end pattern in the include, because ... well, they are consumed. As an example, single-quoted strings in Python are opend and closed by `'` and literal single quotes in the string are produced with `''`. If regular expression matching is applied to a Python string like `r'(some unclosed match'` then the included regular expression syntax matches a begin-end pattern at the opening paren and proceeds to consume all characters *for the outside* until a closing paren is found or EOF is reached. This consumes the closing `'` too. The only way to solve this is to write the included patterns in a way that they can match the closing string denominator in a way that terminates all contexts back to the string match without consuming the end character so that the string begin-end pattern can match it. This would be done using look-aheads. While this is by itself possible, it would be extremely annoying to deal with all possible way of defining a string and thus also all the different string termination sequences (and their escape sequences too!) and include that in all sub-patterns that the include defines.

So, how does `.sublime-syntax` solve this shortcoming? The keyword is the almighty and highly underrated `with_prototype`. It does exactly what we need because it can add the specified patterns to **all subpatterns** in the pushed (or included?) context.

Example:
```yaml
- match: ru?'
  push: source.regexp.python
  with_prototype:
    - match: "''"
      scope: constant.character.escape.single-quote.python
    - match: (?=')
      pop: true
```
And that's it. Issue fixed.

`.sublime-syntax` has even more advantages, but even this advantage alone warrants the new format.

Conclusion: `.sublime-syntax` > `.tmLanguage`

PS: I still really want to make a proper Python syntax def using `.sublime-syntax`, as I have mentioned at the PyI repo a couple times, but sadly there are reasons why other things have higher priority. I really want to avoid working on a pull request that ends up unmergable because of changes happening in parallel. Syntax definitions are really prone to becoming unmergable quickly.

**Comment by jrappen** [comment]
@MattDMo leaving some links here for you as follow up on the topic:

* https://github.com/sublimehq/Packages/commits/master
* 585e986
* b4bd1d1, 12bab0d and 53f8e5e
* #56, #57, #60 and #61

**Comment by wbond** [comment]
I think @FichteFoll explained some of why the new syntax files can handle more complex situations.

Jon explained what is new about the `.sublime-syntax` files at https://forum.sublimetext.com/t/syntax-fun/14830. Just using the YAML version of tmLanguages files wouldn't deal with the changes from `begin`/`beginCaptures`/`end` to `push`/`set`/`captures`/`pop`.

In terms of converting `.tmLanguage` files to `.sublime-syntax`, there is a built-in command that should do most of the work. I haven't used it myself since I don't have any language grammars to convert. To use it:

 1. Open a file that uses your `.tmLanguage`
 2. Open the **Tools** menu and select **New Syntax from *Your Language*.tmLanguage**

This will create a new view with the converted grammar. At this point you could tweak it to take advantage of the explicit parser stack control for complex situations.
