### ISSUE TITLE
Highlights not working in PHP within Javascript code

### ISSUE THREAD

**Issue by kekatxxx** [sublimehq/Packages#1168]
Hi,
I encountered a problem with a PHP file with Javascript instrucions in the <HEAD> part.
When, inside a Javascript funcion, I insert a PHP instrucion, the highligh simply stop to work corretly.

This is the line when It starts to appear:
![imagen](https://user-images.githubusercontent.com/2410547/30772257-52946f04-a058-11e7-95fa-37f8c0e50025.png)

Following the code, this is how a Javascrpit funcion is highlighted:
![imagen](https://user-images.githubusercontent.com/2410547/30772268-97b23e9a-a058-11e7-87f6-7982d0bcb215.png)

Here you find the full file (I cutted a little bit), so you can reproduce the problem.
Thanks!
[bok_pre_edit_test_bug.zip](https://github.com/sublimehq/Packages/files/1326450/bok_pre_edit_test_bug.zip)

**Comment by BenjaminSchaaf** [comment]
The same [seems to be try for css highlighting](https://forum.sublimetext.com/t/syntax-highlighting-bug-php-css/52911).

**Comment by deathaxe** [comment]
Don't think there is an "easy" solution with more than 2 syntaxes being involved which embed include push into each other.

The point here is, PHP includes HTML using `with_prototype` to inject code to pop HTML off stack or even push another PHP context onto stack. All of that is applied to the embedded syntaxes of HTML (CSS, JavaScript) as well. In case of popping HTML off stack to continue highlighting PHP code there is no solution to push back into CSS because the context information are lost.

Maybe there are possible approaches via `extends:` but complexity seems to explode at this point. I guess we might need to extend any involved syntax to inject PHP in a sane way and then put them together again.
