### ISSUE TITLE
Invalid scope in JS export statement

### ISSUE THREAD

**Issue by skyronic** [sublimehq/Packages#1309]
Using dev build of Sublime (3153)

Scope of some code in built-in JS implementation

![image](https://user-images.githubusercontent.com/80173/32850862-6d7de4b4-ca59-11e7-8c25-d5886c7bb7f7.png)

Same file and location with the Babel package:

![image](https://user-images.githubusercontent.com/80173/32850907-8c84fef6-ca59-11e7-8666-e4bf51968c66.png)

**Comment by n-kort** [comment]
#1302 probably related and relevant.

**Comment by Thom1729** [comment]
This behavior is correct. The `export default` form requires a trailing semicolon. In this example, there is no semicolon, so the syntax will assume that the exported expression continues until it reaches either a semicolon, an unexpected character, or a lookahead indicating that the automatic semicolon insertion algorithm would add a semicolon. A related example:

```js
export default {
    foo: 42
}
/* some comment */
['foo'];
```

This will export `42`. The line `['foo']` is not an array literal, but a property access. See [this comment](https://github.com/sublimehq/Packages/issues/1302#issuecomment-343687528) for more details.

Previous versions of the JavaScript syntax handled this incorrectly, resulting in a number of bugs. PR #1009 restructured the syntax definition so that it would systematically do the right thing in these sorts of cases. Unfortunately, the Vue syntax assumes that when the closing `</script>` tag is encountered, the JavaScript syntax will only have the `main` scope on the stack. The Vue syntax will have to be modified to handle embedded JavaScript correctly.

**Comment by Thom1729** [comment]
@skyronic Since we've sorted out the Vue stuff, can this issue be closed?

**Comment by wbond** [comment]
This appears to be resolved now
