### ISSUE TITLE
PHP .php.inc extension

### ISSUE THREAD

**Issue by KvanSteijn** [sublimehq/Packages#134]
For all my projects i used .php.inc extension. Current version of Sublime doesn't support this extension.
See for more information about this extension: http://stackoverflow.com/questions/7129842/what-is-inc-and-why-to-use-it

**Comment by kopeboy** [comment]
Also PHP files with other extensions (like .module - Drupal related) are not recognised and I can't even select the PHP syntax from the View menu!
So I basically get NO highlighting.. :-1:

**Comment by wbond** [comment]
For the time being, you should be able to use the menu *View > Syntax > Open all with current extension as…*.

@kopeboy What happens when you try to manually select the PHP syntax?

**Comment by kopeboy** [comment]
The problem was that I couldn't select the PHP syntax (option disabled, like many other formats).
That was weird, actually I can't replicate now :/ 

Ok then, Sublime wasn't recognising PHP automatically on .inc and .module files, but doing View > Syntax > Open all with current extension as…. works. Thank you.

**Comment by jfcherng** [comment]
I remember that there is a way in a synatx file to set syntax depending the first line of the file.

**Comment by wbond** [comment]
Yeah, we chose not to switch `.inc` files over to PHP since ASP uses that extension also. Unfortunately, the HTML syntax will be picked up even if we add `.php.inc` as an extension to PHP, I imagine due to the fact that HTML comes first alphabetically.

@jfcherng just submitted 9aadfea7adfeaaa6f80cbdc262ebe6664109b509, which will cause files starting with `<?php` to use the PHP syntax. Hopefully this should solve the issue for most people, and then others can use *Open all with current extension as…*.
