### ISSUE TITLE
Url highlighting

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/Packages#1363]
[Feature Request] would you consider adding a scope name for urls, like in markdown, for other syntaxes.

**Comment by keith-hall** [comment]
The C# and PHP syntaxes already have this in comments, but they don't use the same logic as Markdown:
https://github.com/sublimehq/Packages/blob/18a2d34340d9a946246ed5baf98dc9b4f390d95b/C%23/C%23.sublime-syntax#L88-L89
https://github.com/sublimehq/Packages/blob/5a28b6650747ca6ecda682582546ec45fd8bbd7b/PHP/PHP%20Source.sublime-syntax#L1120-L1121

**Comment by AmjadHD** [comment]
why only in comments and why only C# and PHP ?

**Comment by FichteFoll** [comment]
Because it has to be added explicitly and everywhere they should be matched.

I honestly believe that highlighting (and doing other stuff) with URLs is plugin area, since this doesn't actually have anything to do with the syntax you're working with most of the time.

**Comment by Thom1729** [comment]
I concur. Adding URL highlighting to, say, the JavaScript syntax would be inappropriate because the JavaScript language has no concept of URLs. There are some languages like Markdown in which URLs have real syntactic significance, and these languages generally do highlight URLs as appropriate.

Adding URL highlighting to the core packages would be a tremendous undertaking, and it's unlikely that third-party packages would follow suit. In addition, because some languages *do* have syntactically significant URLs, such an effort would inevitably lead to conflict between the correct specific behavior for a certain language and the generic behavior for languages in general. Furthermore, we would be opening ourselves up to the possibility that a language that does not currently have syntactically significant URLs will gain them in the future, at which point we would probably have to make a breaking change to that syntax definition.

A plugin-based solution has none of these problems. It would be much easier to implement, it would work with every syntax without interference, and it would be simpler for a user to configure (e.g. turn it off). If you are dissatisfied with the popular [Clickable URLs](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText) package, then I would open an issue there with your suggestions, or simply fork it and modify it however you'd like. (It doesn't look very complicated.)

**Comment by FichteFoll** [comment]
Other alternatives to Clickable URLs that I digged up:
https://packagecontrol.io/packages/Open%20URL
https://packagecontrol.io/packages/Open%20In%20Browser

**Comment by deathaxe** [comment]
ST got pretty smart in recognizing URLs and opening them in web browser even without requiring syntax support.

Otherwise I am with @Thom1729 to not add highlighting to syntaxes which don't have special concepts for them.
