### ISSUE TITLE
[Ruby] Certain ligatures are not working

### ISSUE THREAD

**Issue by didroe** [sublimehq/Packages#1387]
Some ligatures aren't working when using Ruby syntax. The ones I've found so far are `->` and `!=` but there may be others. I assume this is an issue with the syntax definition as they work fine in Plain Text syntax.

Here is a screenshot from Ruby syntax:
![image](https://user-images.githubusercontent.com/854372/34879546-808ee584-f7a5-11e7-98c5-9eef42ab1ac1.png)

And here's what it looks like in Plain Text mode:
![image](https://user-images.githubusercontent.com/854372/34879496-5b93a5a8-f7a5-11e7-8caa-0feda36812f6.png)

Potentially relevant info:
* I'm using build 3156 of Sublime.
* I'm using the font "MesloLG S" from [here](https://github.com/rojiani/Ligaturizer)

**Comment by wbond** [comment]
Yes, this likely means those operators aren't defined in the syntax, or the disparate parts are matched before the combination. This would lead to it picking up `-` and `>` separately. Similarly for `!` and `=`. Most likely no one noticed because they were the same color.

If you are so inclined to contribute, the syntax def seems to handle them around https://github.com/sublimehq/Packages/blob/master/Ruby/Ruby.sublime-syntax#L313-L385. From glancing at it, it looks like there is a match for `!+` (one or more exclamation marks before the match for `!=`.

When fixing these, it would probably make sense to add some tests to make sure we don't regress in the future.

**Comment by skunkworker** [comment]
@wbond I found some more incorrect ligatures that apply for Ruby's syntax.

![screenshot 2018-09-06 00 36 56](https://user-images.githubusercontent.com/2637951/45139450-06e4a700-b16d-11e8-905a-dd249302c87e.PNG)
![screenshot 2018-09-06 00 36 51](https://user-images.githubusercontent.com/2637951/45139451-06e4a700-b16d-11e8-869e-035cac5d3c40.PNG)

What is the best way to change this syntax? Add more options and exceptions to the `keywords:` or modify the `operators:` ?

**Comment by keith-hall** [comment]
I would guess add an exception to `https://github.com/sublimehq/Packages/blob/c76ba68d0a5368255e5fb57f15c1fc91f20829dd/Ruby/Ruby.sublime-syntax#L328` so that `||` and `!` won't match if followed by `=`, so that https://github.com/sublimehq/Packages/blob/c76ba68d0a5368255e5fb57f15c1fc91f20829dd/Ruby/Ruby.sublime-syntax#L338 and https://github.com/sublimehq/Packages/blob/c76ba68d0a5368255e5fb57f15c1fc91f20829dd/Ruby/Ruby.sublime-syntax#L341 will match correctly.
I'm not sure about `->`, but perhaps it should be added to the `operators` context, as the similar `=>` is handled there.
For heredocs, you can add a negative lookahead to https://github.com/sublimehq/Packages/blob/c76ba68d0a5368255e5fb57f15c1fc91f20829dd/Ruby/Ruby.sublime-syntax#L338 so that `<<` doesn't match if followed by `-`.
For the hex ligature on e.g. `0x44`, it seems that it is already scoped as one token so should work...
```
view.extract_tokens_with_scopes(sublime.Region(0, view.size()))
[((0, 4), 'source.ruby constant.numeric.ruby ')]
```
