### ISSUE TITLE
[LaTeX] lstnewenvironment breaks highlighting

### ISSUE THREAD

**Issue by rasky** [sublimehq/Packages#1399]
`\lstnewenvironment` from package `listing` allows to create new environments that are customized listings. For instance:

```latex
\lstnewenvironment{python}
    {\lstset{language=python,
    basicstyle=\small\ttfamily,
    numbers=left,
    numberstyle=\tiny\color{gray},
    backgroundcolor=\color{lightgray},
    firstnumber=auto
    }}
    {}

\begin{python}
print "Hello world"
\end{python}
```

The problem is that it severely breaks syntax highlighting, because Sublime doesn't understand that the new environment is a verbatim, so anything can happen in there; for instance, an unbalanced `$` makes the rest of the document be in math mode.

**Comment by FichteFoll** [comment]
The syntax parser is unable to store this kind of information, so it cannot infer from the name `python` that it is within a verbatim environment. You should look to using styles in optional arguments to `\begin{lstlisting}` or have an alias for `lstset` prior to the lstlisting environment. Alternatively, you could patch the syntax to recognize a `python` environment as a verbatim for Python (with syntax highlighting inside), but that will then be active for all files and not just where the environment is defined.

**Comment by rasky** [comment]
Would a convention be acceptable? Something like using `verbatim-python` instead of `python`.

**Comment by FichteFoll** [comment]
The problem is that this would then in theory have to be added for all other languages as well, and that it's an arbitrary name. Syntax inclusion for the lstlistings and minted packages already takes about [one third](https://github.com/sublimehq/Packages/blob/ce7af4d6177d0340230893e49742070ae4143246/LaTeX/LaTeX.sublime-syntax#L725-L1370) of the syntax definition and adding more aliases would only increase the redundancy. And those are widely used packages and environment names.
