### ISSUE TITLE
[PHP] array indent

### ISSUE THREAD

**Issue by jbennecker** [sublimehq/Packages#140]
when reindenting php arrays i get the following:

```
public $helpers = [
'Profile',
'Session',
'Text',
'Time',
];

public $test = array(
    'Profile',
    'Session',
    'Text',
    'Time',
    );
```

i expect:

```
public $helpers = [
    'Profile',
    'Session',
    'Text',
    'Time',
];

public $test = array(
    'Profile',
    'Session',
    'Text',
    'Time',
);
```

does anyone know how to fix this?

**Comment by james2doyle** [comment]
+1 for this format style

**Comment by jfcherng** [comment]
Currently, for users, I would recommend using [php-grammar](https://packagecontrol.io/packages/php-grammar) to replace the official PHP package.

**Comment by jbrooksuk** [comment]
Is there any chance we'll see `php-grammar` being merged into core?

**Comment by wbond** [comment]
@jbrooksuk Replacing an existing grammar with a new one takes a bit of consideration and testing. For instance, there were significant changes to JavaScript, which has caused no end of complaints about changing syntax highlighting, and now indexing performance issues.

Ideally I'd want the author to be interested in contributing it, then we'd have to ensure there were tests and do some performance measurements on it.

Most of the big PRs haven't happened because of the significant amount of time that must go into reviewing them, versus all of the smaller PRs that are easier to review and test.
