### ISSUE TITLE
[D] Grammar and ligature support has some oddities

### ISSUE THREAD

**Issue by TheGag96** [sublimehq/Packages#1403]
(Repost from the Sublime forum)

I found out the other day that Sublime finally got ligature support, which is great. A lot of stuff from Fira Code works beautifully, but there are still some nitpicks I have that apparently stem from the way language grammars affect ligatures.

Some stuff I'm noticing:
* the `..` operator often [makes Sublime think a float literal is on the right hand side if a numeral is there](https://imgur.com/a/G0ujx)
* the `=>` operator for lambdas doesn't get made into the pretty Fira Code arrow
* Stuff like `0x10` doesn't get the smaller x character (though this is the case for every other language too, as well as `+-*:`; ThomSmith pointed out this is due to lack of support for contextual alternatives)
* `///` is grouped as a double slash and one single further apart instead of the triple slash (this happens in C as well)
* `/=` doesn't get combined like in C
* `||=` doesn't get recognized in D nor C (yet `|=` works just fine in both)
* `~=` doesn't get made into the tilde with a line under it (don't know whether it should be that way or not; this would be for concatenation)

As a side note, after an improvement update to the D grammar about two years back, [class code became highlighted entirely with the "class" color](http://i.imgur.com/RxqTqoP.png). I've been dealing with this until now by setting that color to match regular text.

Anyways, hope to see these improvements. Thanks to the wonderful Sublime team!

**Comment by wbond** [comment]
All of the ligature issues are almost certainly related to the (current) poor quality of the D grammar. What we really need is someone who knows a lot about D and who is willing to learn some about Sublime syntaxes so that we can mentor and provide feedback on improvements or a rewrite of the syntax.

If you are interested in helping out, the following would be some good reading: 

 - http://www.sublimetext.com/docs/3/syntax.html (be sure to read the section at the end about testing)
 - http://www.sublimetext.com/docs/3/scope_naming.html

The C# syntax may be a good reference since @keith-hall has done a ton of work on that, and is one of the most active contributors from the community to this repo.

**Comment by BenjaminSchaaf** [comment]
This should have been fixed by #1850 (Other than `||=` as that isn't a operator in D afaik)

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
