### ISSUE TITLE
[Python] Poor invalid scopes while typing

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#1441]
I've been noticing lots of invalid scopes flashing the Python syntax as I've been refactoring a codebase over the past few days. These should be left to a linter, since it makes the editing experience kind of jaring.

Wrapping a value in a method call (cursor after `.`):

```python
a = foo.'bar'
```

Adding a parameter to a function/method call (cursor after `.`):

```python
foo.bar(baz., True)
```

Need to be improved by better pairing (cursor after `'`):

```python
regex = r'
```

I think there are a few others, but I don't recall off of the top of my head.

**Comment by FichteFoll** [comment]
Yeah, I notice this too and also know where it's coming from, but haven't bothered looking for a proper fix. In short, I tried highlighting invalid characters after dot accessors, but this is quite bad experience while typing inside a line (and not at the end).

**Comment by Thom1729** [comment]
The auto-pairing issue is from the Default keymaps. It won't auto-pair quotes if the character before the cursor is `a-zA-Z0-9_`. I don't know of any good reason for that rule; if there's no compelling reason to keep it, then it could be eliminated. (Of course, because the binding is in the Default package, I can't submit a PR.)

**Comment by FichteFoll** [comment]
There is a good reason for this, notably that you are likely to write a closing quotation mark when directly behind an alpha character. I don't know if there is an easy and general solution for this since, until the quite is inserted, the `r` will be matched as a normal identifier just like any other identifier. I suppose we will need a python specific key binding that checks whether the preceding text could be a string prefix.

**Comment by wbond** [comment]
The issues with `.` were resolved in #1442
