### ISSUE TITLE
[C#] Expression-bodied methods are not parsed correctly

### ISSUE THREAD

**Issue by rolfbjarne** [sublimehq/Packages#1496]
See screenshot:

![screenshot 2018-04-09 10 19 14](https://user-images.githubusercontent.com/249268/38487125-77dbdcac-3bdf-11e8-81f0-7f6651756683.png)

The expression body seems to prevent the syntax highlighting from detecting the end of the fenced code block.

Commenting out the constructor yields expected results:

![screenshot 2018-04-09 10 20 04](https://user-images.githubusercontent.com/249268/38487178-9d81bf80-3bdf-11e8-847d-b81dc0ddc4ea.png)

I'm currently using a locally cloned version of the C# sublime syntax file (992c9b0ea8d720ab7096c958d727e9612ed06172)

**Comment by keith-hall** [comment]
Which syntax are you using to write your Markdown in? I'm guessing not a locally cloned version of the Markdown syntax from this PR https://github.com/sublimehq/Packages/pull/1274?

**Comment by rolfbjarne** [comment]
I don't quite understand the question.

I'm using the tip of master as of a few minutes ago.

**Comment by keith-hall** [comment]
No problem, I'll try to explain better. You are writing fenced code blocks that contain C# code in a Markdown file. Probably it is a bug in the Markdown syntax you are using. If you were using the Markdown syntax from this repo, it wouldn't highlight the C# code at all. If you were using the Markdown syntax from the PR I referenced, it would work fine. So probably you need to report the bug elsewhere (i.e. on the relevant issues list for the Markdown syntax highlighting package you are using). Said syntax should probably make use of `embed`/`escape` actions as per the referenced PR, or use `with_prototype` to detect the end of the code fence, otherwise the problem you described will occur. Making changes to the C# syntax in an attempt to work around some third party package bug isn't desirable (to me at least - I contribute quite a lot to the C# and Markdown syntax definitions on this repo).

**Comment by keith-hall** [comment]
Sorry, I was concentrating on the wrong part of your issue... I'll see if I can make a fix so that the C# syntax will recognize expression bodied methods when used on a constructor.
