### ISSUE TITLE
[Markdown] illegal empty line after file listing

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1499]
The `*` are interpreted as beginning of `italic` text which are not terminated. Therefore the line after is highlighted illegal. The text is valid markdown though and should not displayed in italic style at all.

```
    - *.mdat *.svar files from CreateMyConfig
```

![screenshot](https://user-images.githubusercontent.com/16542113/38695959-1483bd62-3e8e-11e8-851f-e03fe2b2923f.png)

**Comment by FichteFoll** [comment]
To prevent ambiquity, `\*.mdat and \*.svar` should be used. I'm not on top of the CommonMark spec to determine whether the two asterisks are detected as being an inline italics block or not.

How github renders it:

- *.mdat *.svar files from CreateMyConfig

**Comment by keith-hall** [comment]
Even if we "fix" it to not treat it an asterisk as beginning an italic markup if it is followed by an asterisk on the same line that doesn't close the markup, perhaps using something like:

```diff
   italic:
-    - match: '\*(?=\S)(?!\*)'
+    - match: '\*(?=\S)(?!\*)(?![^*]+ \*)'
```

then the next asterisk will still get highlighted as beginning italic markup...

![image](https://user-images.githubusercontent.com/11882719/38723459-d7b33f12-3f09-11e8-8996-a97c22ae4316.png)

we'll always have this problem that we can't parse CommonMark exactly according to the spec, because we can't see over line boundaries. I agree with @FichteFoll that it's best practice to escape the asterisks, or perhaps put your file globs inside backticks.

**Comment by deathaxe** [comment]
I'd honestly wouldn't have realized any issue if the empty line wouldn't have been highlighted illegal.

Even though parts of the first line are presented italic, the scope should silently pop off, if it hits an empty line, instead of highlighting it illegal - as it is not.

- Github is smart and does not print the line itallic.
- Using MarkdownPreview with python's markdown processor, the first `*.mdat` is presented italic as it ignores the space in front of `*.svar`. Not correct, but doesn't highlight anything illegal.

**Comment by FichteFoll** [comment]
You have a choice between highlighting italics across line boundaries and enforcing  ambiguous asterisks to be escaped through invalid scopes, or only highlighting single-line regions.
