### ISSUE TITLE
[PHP] No highlights multilingual files

### ISSUE THREAD

**Issue by Bobsans** [sublimehq/Packages#150]
If the file is present in php script on js or css styles, does not work syntax highlighting for these languages.

Screenshot: [https://yadi.sk/i/vvPE11dJobefu](https://yadi.sk/i/vvPE11dJobefu)

**Comment by wbond** [comment]
I believe the bug here is that the parser is seeing `//--></script>` and not picking up the closing script tag since it sees the line comment while in the JS context.

We should be able to get this fixed up.

**Comment by PMickael** [comment]
Screenshots :
![image](https://cloud.githubusercontent.com/assets/122271/12952090/93a85254-d015-11e5-8168-e21a807b1e53.png)
[HTML instead of PHP]

![image](https://cloud.githubusercontent.com/assets/122271/12952214/ff56b298-d015-11e5-8c94-d56515e7abde.png)
[HTML instead of HTML(Jinja2)]


Should be :
![image](https://cloud.githubusercontent.com/assets/122271/12952236/15fcea4e-d016-11e5-90bd-8c990f8a15ea.png)

![image](https://cloud.githubusercontent.com/assets/122271/12952228/0d6bda5c-d016-11e5-8115-5d44e4e816d9.png)

I have to set the syntax manually

**Comment by wbond** [comment]
@PMickael In the first example, does your file end in `.html`? If so, use the *View > Syntax > Open all with current extension as…* menu and you should be good. Same thing for the second.

**Comment by wbond** [comment]
This should be fixed by 16c5f8ff8da5f9d13ae0029183cd52e17299c045.
