### ISSUE TITLE
[HTML] Syntax highlighting broken for certain values of the script's type attribute

### ISSUE THREAD

**Issue by CorpulentBrony** [sublimehq/Packages#1536]
Just upgraded to build 3170 and noticed that JavaScript inside a `<script>` tag where the type is `application/javascript` is no longer rendered as JavaScript syntax but instead is just plain text. This doesn't conform to HTML spec (https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) which states any JavaScript essence MIME type match (https://mimesniff.spec.whatwg.org/#javascript-mime-type) should be considered JavaScript.

I noticed the same issue with JSON embedded inside scripts (specifically with the type `application/ld+json`).

**Comment by Thom1729** [comment]
For JavaScript, should be fixed by #1539.

I'm not quite sure what you're saying about JSON. The spec does not indicate that JSON data should be treated in any special way. We could conceivably add support for more languages in `<script>` tags (and we do specially handle embedded HTML since #1510), but we're generally hesitant to add nonstandard features that could conflict with future usage.

This issue should be tagged HTML, not JavaScript.

**Comment by CorpulentBrony** [comment]
What I meant was that previously JSON was being treated as JavaScript when appearing in `<script>` tags which meant it was formatted.  Not really necessary, though scripts with a type of `application/ld+json` are very common as they are used for JSON+LD schema markup.
