### ISSUE TITLE
[JavaScript] syntax-quote broken when flowtype used

### ISSUE THREAD

**Issue by taoeffect** [sublimehq/Packages#1547]
Using Sublime 3.1.

![screen shot 2018-05-09 at 12 04 08 am](https://user-images.githubusercontent.com/138706/39795207-9586dbd6-531c-11e8-9b5f-13ec51acbcfe.jpg)

The `this` at the end of `static fromObject (obj, hash): this` breaks it.

EDIT: note that [JSCustom](https://forum.sublimetext.com/t/cannot-load-markdown-files-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/36720/9) fixes this

**Comment by Thom1729** [comment]
The core JavaScript syntax does not support Flow type annotations. The core syntax only highlights standard JavaScript, including many experimental standards-track features but excluding nonstandard extensions such as Flow, JSX, and TypeScript.

By supporting Flow annotations, the core syntax would be making an arbitrary choice that could conflict with future standard JavaScript features or with other nonstandard extensions that users could want. In addition, the core syntax would be on the hook to maintain whatever extensions it supported as those extensions evolve.

As the author of [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom), it's probably not surprising that I recommend that package for highlighting Flow and JSX. It's built directly on top of the core JavaScript syntax but offers configurable support for various nonstandard extensions. If the core syntax did implement a specific nonstandard type system, that might actually interfere with JS Custom's ability to support alternative systems.

Because the problem you describe is outside the scope of the core JavaScript syntax, this issue should probably be closed. If you have any issues with JS Custom's Flow typing support, please don't hesitate to [open an issue](https://github.com/Thom1729/Sublime-JS-Custom/issues).

**Comment by taoeffect** [comment]
@Thom1729 sounds reasonable, thank you.
