### ISSUE TITLE
[JavaScript] Some identifiers are being scoped as separate tokens

### ISSUE THREAD

**Issue by cixtor** [sublimehq/Packages#1554]
### Summary

While reviewing some JavaScript code, I noticed that some keywords were being highlighted in sections with no special meaning. Later I noticed that the same issue was happening in other parts of the view, not just the editor, the "Find…" form, for example. Notice that this only happens with the Celeste UI color scheme, I tried other options and the issue is not reproducible.

### Expected behavior

* Keyword `foo.id` should be colored all in blue.
* Text in search form should not be highlighted.

### Actual behavior

* Keyword `foo.id` is highlighted in blue, but the letter `i (eye)` contains a different color.
* Text in search form is being highlighted with different shades of blue and purple.

<img width="685" alt="aaa" src="https://user-images.githubusercontent.com/1933999/39788249-6f235dc2-52de-11e8-8270-d50741029bc7.png">

### Steps to reproduce

1. Create a new _(empty)_ tab.
2. Copy and paste the code below.
3. Select menu "Find > Find…"
4. Search the word `history`

```
// Code to showcase the bug.
function foobar(foo) {
    return Foobar.fetch(uuid, foo.id);
}
```

### Environment

* Mac OS 10.13.4 _(x86_64)_
* Sublime Text 3.1 Build 3170

**Comment by Thom1729** [comment]
Ooh, this one is interesting. Apparently regexp capture groups always cause the parser to split matches at the capture boundaries. This could be fixed in the syntax by replacing all of the unnecessary capture groups matching builtin property names with non-capturing groups. (Or by not special-casing those property names, which I don't see much point to anyway.)
