### ISSUE TITLE
[HTML] grammar does not allow a comment ending in --->

### ISSUE THREAD

**Issue by gerardroche** [sublimehq/Packages#1561]
In previous versions HTML comments ending in `--->` were highlighted as invalid. Example:

```
<!-- invalid ----->
```

> Note that the grammar does not allow a comment ending in `--->`. The following example is not well-formed.
> 
> ```
> 
> ```
> https://www.w3.org/TR/REC-xml/#sec-comments

**Comment by michaelblyons** [comment]
See #1389 which updated the behavior you're looking for from #1139.

**Comment by blunket** [comment]
#1139 was my PR. it seems like the requirements have indeed changed since then, and #1389 fixed them -- the current code matches the requirements/validator perfectly.

You linked XML requirements, but tagged this as an issue within the HTML package. The HTML package is perfectly matching HTML specs. I would open a new issue or rename this one.

I do see that the actual issue we fixed in #1139 is now an issue within the XML package.

![image](https://user-images.githubusercontent.com/17580512/40245836-54af7c68-5a8c-11e8-8b0c-f63648a4f8de.png)
