### ISSUE TITLE
YAML highlighting issue

### ISSUE THREAD

**Issue by ZorroJimenez** [sublimehq/Packages#1602]
Currently, this YAML file highlights incorrectly:

    x: 10
    y: 20
    z: 30

Namely, the 'y' appears in red italics because the syntax highlighter treats as short for the boolean value 'Yes'. But I think that such highlighting should only occur if 'y' appears as a value.

**Comment by michaelblyons** [comment]
See #1113

**Comment by FichteFoll** [comment]
See also https://forum.sublimetext.com/t/bug-in-yaml-syntax-highlighting/37094/12?u=fichtefoll.

**Comment by FichteFoll** [comment]
Does anyone have a strong opinion on this? The most pouplar Python YAML parser, PyYAML, still only parses 1.1 where `y` literals are interpreted as booleans. The highlighting helps a lot in finding those errors, but very occasionally it *does* get in the way in case you are in a 1.2 environment and know that these are in fact interpreted as strings.

I believe, following our backwards-compatibility trend of the past years, highlighting of these scalars as booleans should remain, but I sure wish YAML 1.1 and this problem never existed in the first place.

**Comment by rwols** [comment]
I guess I can say a few words about this :) Consider example 2.24 from http://yaml.org/spec/1.1/
```
%TAG ! tag:clarkevans.com,2002:
--- !shape
  # Use the ! handle for presenting
  # tag:clarkevans.com,2002:circle
- !circle
  center: &ORIGIN {x: 73, y: 129}
  radius: 7
- !line
  start: *ORIGIN
  finish: { x: 89, y: 102 }
- !label
  start: *ORIGIN
  color: 0xFFEEBB
  text: Pretty vector drawing.
```
Here, the `y` key is a coordinate of a point. We know this because that is contextualized by the surrounding tags. A parser may or may not understand that and map this data to a point type. So wether `y` is a boolean or not depends on the accompanying tag.

Seeing as the type of a scalar depends on the tag, I think we should actually not highlight scalars at all. It's okay to scope numbers as numbers, that's a good heuristic. But we cannot hope to answer more complex questions like "is this a string or a boolean or some application-defined datatype?". I know PyYAML is the de-facto parser for Python, but there are other parser libraries out there.

I don't personally mind the `y` character being a different color in my color scheme but I can understand why that might come across as presumptuous of the current syntax.

**Comment by FichteFoll** [comment]
Since this was also mentioned for the 'on' key used in Github Actions in #2329 (and I've also worked on a couple of these in the past week), it's time for an update, I suppose.

Ideally, I'd like to have some statistics on which YAML parsers interpret the 1.1 implicit boolean plain scalars and how often or frequently they are used. By far the most documents I have edited personally are using YAML 1.2 parsers, so much that I couldn't even remember any other than documents read using pyyaml (and not ruamel.yaml). I wanted to err on the safer side in the past and implicitly ask the user whether the highlighting he sees there is what he would expect or can live with. After all, if you know about this quirk, you're more likely to read over them when you know you're in YAML 1.2 than when you don't know about it and are in 1.1. 

However, I believe we should go with the times as well and I haven't heard any positive feedback on the highlighting of these obscure plain scalars, so I believe it's on the user to figure this out on their own should they run into problems. While our aim is to be backwards compatible, there is a limit to how much inconvenience you should be able tolerate. Unless someone beats me to it, I'll prepare a PR to remove these matches soon-ish. (If you want to jump right into it, you should also remove matches for the other removed schema types.)

**Comment by FichteFoll** [comment]
A quick check [on the homepage](https://yaml.org/), that has been kept mostly up2date [as far as I can tell](https://github.com/yaml/www.yaml.org/commits/gh-pages), paints a pretty clear picture regarding library support of YAML versions in general. It doesn't say much about which schemas the libraries actually parse. For that, a [schema test suite](https://perlpunk.github.io/yaml-test-schema/data.html) is currently being developed by one of the YAML devs, but that may still take a while until it is completed and at least covers the most popular libraries [also available in docker images for quick testing](https://github.com/yaml/yaml-runtimes).

In general, I'm still not conviced removing the 1.1 highlighting is the correct action, even if just for keys, as YAML in itself does not differentiate between key and value types. I hope for the schema tests to provide more information to base this on, but I remain sceptical.

An alternative could be to duplicate the YAML syntax into 1.1 and 1.2 variants and decide which one to use based on a `%YAML 1.1/2` attribute in the first line. While this is an advertised feature, it is hardly used in actual YAML documents and would still leave us with almost the same problem as we have currently regarding what the default syntax should be.
For YAML 1.3, there is even an [RFC draft for removing directives](https://github.com/yaml/yaml-spec/blob/93484a6b4659093538f5114377c0553668e2fd2f/rfc/RFC-018.md), but 1.3 is still far into the future and probably not relevant here.

**Comment by michaelblyons** [comment]
> An alternative could be to duplicate the YAML syntax into 1.1 and 1.2 variants and decide which one to use based on a %YAML 1.1/2 attribute in the first line.

Maybe a good application of `extends`?

**Comment by FichteFoll** [comment]
That would be a good application, indeed, however:
> While this is an advertised feature, it is hardly used in actual YAML documents and would still leave us with almost the same problem as we have currently regarding what the default syntax should be.

To date, the only kind of YAML documents I've seen that reliably use this attribute are Sublime Text syntax definition (and likely because they are included in every template to create a new file).

**Comment by michaelblyons** [comment]
Right, but we could use YAML 1.2 for the default for `yaml`, `yml`, etc. Then if anyone complains, you just tell them to "Open this extension with..." the 1.1 version.

I'd actually argue that using only `first_line_match` is **already** insufficient because ST doesn't let the sidebar sniff syntax selection from first line match... only from extension. So YAML files in the sidebar wouldn't be able to get an icon from your theme. And if there were extensions configured for either a YAML 1.2 or 1.1, the `first_line_match` would never be invoked anyway.
