### ISSUE TITLE
[JavaScript] `extends` is painted like a class name

### ISSUE THREAD

**Issue by user-9826342** [sublimehq/Packages#1636]
Code:

```js
~class extends a{static a(){}}
```

Expected:

![](https://user-images.githubusercontent.com/39801377/41231131-5bc34e36-6d82-11e8-813f-1f87c9762cb7.png)

Actual:

![](https://user-images.githubusercontent.com/39801377/41231139-6276f214-6d82-11e8-9d84-fc764d0c40b5.png)

**Comment by Thom1729** [comment]
Already fixed by #1614.

**Comment by user-9826342** [comment]
Are you sure? I merged your patch locally to master branch syntax file and the issue is still present...

**Comment by Thom1729** [comment]
I'm sure. You can see that in the "actual" example, the token `extends` is marked `entity.name.class`, which is what interferes with the rest of the expression. You will observe that if you add an explicit class name, the bug vanishes. I checked out the branch being merged in #1614, and I can verify that the bug is fixed.

**Comment by keith-hall** [comment]
please mention in your issue title which syntax it refers to, it appears to be JavaScript in this case.

**Comment by user-9826342** [comment]
@Thom1729 

You are right, I was merging wrong pr. Closing this.
