### ISSUE TITLE
[Python] Please fix the 'file_regex' in build system configuration

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1655]
Using the current build regex:
https://github.com/sublimehq/Packages/blob/b43d6054c2e9aeb8b8a5f3bc92df4e2a397e9db2/Python/Python.sublime-build#L3

Keeps Sublime Text popping the error on the console:
```
The regular expression must capture filename,line,[column,]message
Please fix the 'file_regex' in build system configuration.
```

Appending `(.*)` to the standard regex, fix the error:
```regex
"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)(.*)", 
```

**Comment by FichteFoll** [comment]
The python errors are a bit special because They are actually tracebacks and have the actual error message as a single line at the end of it, making them extremely unfit for ST's build system error catching and inline error display. I'd almost be inclined to remove the capture entirely, however being able to double-click on the traceback's position checkpoints is still pretty useful.

**Comment by michaelblyons** [comment]
Could you just do an empty capture group, then? `"...line (\d*)()",`?

**Comment by FichteFoll** [comment]
So, I tried reproducing this, but when I receive a traceback with the Python build system from `master`, i.e. `"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",`, I don't get any such message. Neither as a dialog nor in the console.

![2018-12-27_23-13-00](https://user-images.githubusercontent.com/931051/50495976-f9f60700-0a2c-11e9-818a-7eeb227be99d.png)

Console:
```
Running python -u "/home/fichte/.config/sublime-text-3/Packages/Python/syntax_test_python.py"
```

**Comment by FichteFoll** [comment]
So presuming this isn't actually a bug (?), I don't think there is anything that can be done about the current build system here. I mean, as I mentioned, the output format of Python's interpreter is not compatible with ST's build systems and adding an empty capture group so that the recorded message is empty would effectively disable error phantoms entirely (or rather make their content empty), which is barely more useful than currently because the phantoms become quite small. So instead I'd rather do nothing and let the user decide whether they want to see the phantoms or not and then disable them if they don't (in their global or syntax-specific settings).


![2018-12-27_23-15-55](https://user-images.githubusercontent.com/931051/50496027-6244e880-0a2d-11e9-92cb-706256987506.png)

**Comment by evandrocoan** [comment]
> So instead I'd rather do nothing

Then, the current message would still showing up?
```
The regular expression must capture filename,line,[column,]message
Please fix the 'file_regex' in build system configuration.
```

In this case, I would suggest to at least show it in one liner for cleaner log:
```
The regular expression must capture filename,line,[column,]message
```

I also just tested it with build 3184 and message did not showed up for the same `file_regex`. I guess it is fixed, then I am closing it.

**Comment by FichteFoll** [comment]
I'm saying that I can't reproduce the problem with the "current message" you're quoting. Maybe someone else can chime in here? Or try in a clean ST environment in case this is caused by a third-party package.

Also, to my knowledge you really don't *need* a capture group for the message part. If there are only 2 groups, the entire message will be used as the message. Maybe there's only one capture group in some build system?

**Comment by evandrocoan** [comment]
> I'm saying that I can't reproduce the problem with the "current message" you're quoting.

I am saying that too. That problem was reproduced with the version of Sublime Text I had by the time I wrote this issue.

Today, I tried with the latest version I have installed, and I cant reproduce it anymore. (I did not changed the `file_regex` or anything, just the Sublime Text build.
