### ISSUE TITLE
How to make "References" section appear

### ISSUE THREAD

**Issue by dten** [sublimehq/Packages#1669]
I have a custom syntax and it works nicely for going to definitions, I would also like the "References" section to appear. 

I have found if i mark things as `meta.function-call variable.function` then things show up. Is it possible to use other scopes to make things appear in references. I can't find any documentation about them.

I noticed they also seem to jump languages, I see javascript files appearing as references in other languages. Is it possible to reduce the scopes the references are looking at.

**Comment by wbond** [comment]
No, it isn't possible to have other scopes show up since those are the "correct" scopes. The scope names are a historical artifact of popular syntaxes, and are now enshrined in the [Scope Naming documentation](http://www.sublimetext.com/docs/3/scope_naming.html).

Currently the References functionality is designed to cross languages, partially because of things like CSS class names moving from HTML to CSS, or JS to CSS, etc. Additionally, lots of languages bind to C libraries, so it allows jumping across FFI boundaries to other languages.

I believe a few users have inquired about adding the ability for the syntaxes that a syntax should reference to be configurable. There is a related issue at https://github.com/SublimeTextIssues/Core/issues/335 which has some discussion and links to stuff on the forum.

**Comment by wbond** [comment]
On a side note, it would be cool if the Rust community would take some to report syntax definition bugs so that we can continue to refine the built-in definition!

**Comment by dten** [comment]
We could do another upstreaming thing I'm sure for Rust.
this particular issue was a for Haskell one I was working on 😉 the current built in sublime-syntax is.. less than great. I wanted to get it to a point that was less shameful and add tests then offer it up to the sublime gods
