### ISSUE TITLE
Kotlin support?

### ISSUE THREAD

**Issue by nkiesel** [sublimehq/Packages#1695]
Could you please add support for Kotlin as well? Seems https://github.com/vkostyukov/kotlin-sublime-package could a a very good starting point

**Comment by djspiewak** [comment]
Jon and Will have already decided that the only mode which will be added to the core for the immediate future will be Swift. The reason for this restriction is there are plenty of third-party packages for most languages (including the one you linked for Kotlin) and at present third-party language modes don't compose well with built-in modes for the same language. This is a technical issue and will eventually be resolved but not at present.

**Comment by hronro** [comment]
Any updates?

**Comment by Thom1729** [comment]
It's very unlikely that Kotlin would be added to the default packages. A new language is a substantial maintenance burden, forever. As far as I know, the only languages added since this issue was created were JSX, TypeScript, and TSX, which:

- Are among the most common languages in use today.
- Are supported out-of-the-box in other major editors.
- Are direct extensions of the existing built-in JavaScript syntax (and serve as built-in examples of syntax extensions).
- Were based on an up-to-date, fully tested third-party package with little revision required.

Kotlin is definitely a real language in real use, but it's not in the same league of popularity as TypeScript or JSX. Neither Atom nor VSCode supports Kotlin by default. Kotlin is a standalone language that could be implemented in high quality by a third-party package — but the existing package is outdated and would probably require a great deal of work or even a total rewrite in order to meet the default packages' quality standards, and it has no tests at all.

Furthermore, it's not clear that a built-in Kotlin syntax definition would be any better than a third-party package like the one linked above. The built-in syntaxes are still maintained largely by the community, and more popular languages like JavaScript and Python receive the most attention. If someone is knowledgeable about Kotlin and motivated to improve its syntax highlighting, then there's already a third-party syntax they could contribute to. And frankly, if a syntax needs a major overhaul, it's a lot easier to do in a third-party package that can be less worried about breaking compatibility.

**Comment by nkiesel** [comment]
Pretty sure that Kotlin would be more popular than a few of the languages you currently support (looking at e.g. D or Pascal here).  But of course I respect your decision.  Best of luck!

**Comment by michaelblyons** [comment]
For lurkers: https://github.com/sublimehq/package_control_channel/pull/9391
