### ISSUE TITLE
[Markdown] Not closing fenced code block with invalid JavaScript code

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1750]
![image](https://user-images.githubusercontent.com/5332158/47405612-c515bd00-d728-11e8-824b-fc268b2d07bd.png)

````
Bug no markdown;

```js
class Research extends React.Component {...})
```

<dd><fieldset>
<fieldset><fieldset>deve-se
</fieldset></fieldset></fieldset></dd>


```

sdf

```


````

**Comment by FichteFoll** [comment]
Works for me. Make sure you're using the correct syntax.

![2018-10-24_17-07-59](https://user-images.githubusercontent.com/931051/47440929-6f382800-d7af-11e8-8e02-8245da9f63a8.png)

**Comment by evandrocoan** [comment]
I think it is because my JavaScript syntax a ReactJS is from https://packagecontrol.io/packages/JSCustom package.

**Comment by Thom1729** [comment]
I'll take a look later and see if I can reproduce.

**Comment by evandrocoan** [comment]
Just one more thing. I am using the latest version on this master branch, but I think I have added a customization to my Markdown fork https://github.com/evandroforks/Packages/blob/master/Markdown/Markdown.sublime-syntax because on FichteFoll picture, there is not highlighting to the embedded JS code.

**Comment by deathaxe** [comment]
The issue is caused by popping off from the `statements` context if a stray brace/bracket/paren is detected and `statements` being included in the main context.

https://github.com/sublimehq/Packages/blob/14a35f641f348b4ee0ead558e5ee474f7255b50f/JavaScript/JavaScript.sublime-syntax#L288

As removing the `pop: true` does not break any existing test, I wonder why it exists.

Another solution was to not directly include `statements` in main, but add its body without the `pop: true`

**Comment by evandrocoan** [comment]
I think @Thom1729 could help. After running investigate:
![image](https://user-images.githubusercontent.com/5332158/49306889-abe7f500-f4ba-11e8-8195-ea30d7482045.png)

That line seems to be added by him earlier this year on the commit:
1. **08/02/2018 19:39** JavaScript - Improved handling of unexpected close punctuation c581495e33d3135dc3b0bdada2b123bb84cf9317

**Comment by Thom1729** [comment]
Should be an easy fix. I'll try to take a look this weekend.

**Comment by evandrocoan** [comment]
If @Thom1729 can "fix" the JavaScript syntax, then, I think both fixes (pull #1755 and @deathaxe suggestion for Javascript)  are welcome because JavaScript should behave better when included by other syntaxes and Markdown would behave better when including some syntax with the same problem.

**Comment by Thom1729** [comment]
I'm not sure there's a general solution on the Markdown side. What we want to do is wrap the embedded context in a guard, but I think that would have to be done manually for each embed.

**Comment by FichteFoll** [comment]
I was just referring to the discussion in #1755, not to the solution, though that might've been misleading. Since I liked the comment by @deathaxe mentioning how the proper fix would be in the JavaScript syntax, I assumed it would be clear that I support that solution instead of the one proposed in the PR. 

My bad if this caused confusion.
