### ISSUE TITLE
[SQL] ANSI SQL

### ISSUE THREAD

**Issue by R0bk** [sublimehq/Packages#1764]
Back at the end of 2016 in #630 there was a brief discussion of different flavors of SQL in sublime. Currently writing code for non mySQL flavors can be quite painful e.g. temp tables (and following text) is commented out.

I was wondering if there ever was a decision surrounding adding an ANSI (or any others) compatible SQL syntax highlighter?

**Comment by keith-hall** [comment]
I believe we are waiting for a future update to Sublime which will allow users to configure (on a global basis - not a project basis due to how the syntax graphs are stored) which concrete SQL syntax should be used, so that this repo can ship multiple SQL syntaxes for each dialect, then each user can choose which one should be used when a syntax references `scope:source.sql`.

**Comment by jrappen** [comment]
@R0bk Maybe you could have a look at and comment on #3046 with some reference links and maybe links to tests for edge cases.

**Comment by deathaxe** [comment]
Fixed by #3046
