### ISSUE TITLE
[JavaScript] for..of

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#1767]
ok:

```js
for(let element of document.querySelectorAll('a[href$=".js"]'))
  element.remove();
```

not ok (`of` not colored):

```js
let element = null;
for(element of document.querySelectorAll('a[href$=".js"]'))
  element.remove();
```

**Comment by Thom1729** [comment]
The problem is that these two cases are very hard to distinguish:

```js
for (Expression; Expression; Expression); // First Expression may not use `in`
for (LeftHandSideExpression in Expression);
```

The JavaScript syntax's expression parsing is very fine-grained, but not quite fine-grained enough for a simple cover grammar to handle both `Expression` and `LeftHandSideExpression` and bail out on `in` or `of`.

I think that the last time I looked at it, I concluded that it would be too much duplicate code for a marginal benefit (you really shouldn't be writing code that hits the `LeftHandSideExpression` case, and the highlighting impact is very small). I think that this is the first time anyone's noticed or complained, which means it's time for me to take another look at it.

**Comment by FichteFoll** [comment]
I did notice this recently when I was working on JS code, but I just assumed it wasn't actually supported by JS (and usually I meant to add a `const` there anyway). Maybe `of` and `in` should just be highlighted when within a for expression?

**Comment by Thom1729** [comment]
This turned out to be easier than expected. I re-used the trick for expressions that don't allow the comma operator. I did find some new bugs in the process, though.
