### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by jrappen** [sublimehq/Packages#18]
* Is there a reason, why `Color Scheme - Default`, `Default`, `Language - English`, `Theme - Default`, `Vintage` are missing from this repo?
* Will you accept people adding new language packages to the current ones?
* Can we add new packages that include executables such as linters, which require not being packed into a `*.sublime-package`? If so, do we mark them with a `.no-sublime-package` file as required by PackageControl?

**Comment by FichteFoll** [comment]
`.no-sublime-package` is a Package Control-only thing.
I would advise against bundling secondary executables, especially if they depend on other runtimes like php or node.

I am, however, curious as to what kind of criteria a package needs to fulfill in order to become a default package. Personally, I haven't used a fair share of the default syntaxes that ST has shipped since version 2.

**Comment by sublimehq** [comment]
I've expanded README.md to cover some of these questions now.
