### ISSUE TITLE
[HTML] the script-html context does not exit properly

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#1827]
Currently, after the following syntax:
```
<script type="text/html"></script>
```
the scope `text.html.embedded.html` remains on the scope stack. I think this is because the `script-html` context includes `main` before it includes `script-close-tag`.

**Comment by deathaxe** [comment]
Your assumption is correct. Changing the order fixes that issue, but triggers another one caused by the strange `<!--` `-->` comment handling within script tags. I guess it is intended to support embedded syntax highlighting even though the content might be commented out, which was often used to support old legacy browsers from the 90s.

If we want to keep that, a solution might be a bit tricky. Needs investigation.
