### ISSUE TITLE
Lua - is it intended that a missing "then" removes subsequent highlighting?

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#1903]
[Screenshot](https://puu.sh/D0lKP.png)

A missing "do" after a "for" does not have the same behavior for example, [screenshot](https://puu.sh/D0lLL.png)

If this is intended could someone help me edit it locally for myself? I find it super distracting while I'm writing code.

**Comment by FichteFoll** [comment]
Hm yes, it shoudl probably fail gracefully when a `then` can't be found. The problem is whether an if-end block should be opened or not in the internal representation because that affects whether a following `end` will be matched and associated with the opening `if` or whether it is considered to be extraneous.

**Comment by RheingoldRiver** [comment]
I like how for loops behave right now when they're incomplete, so I'd be happy with copying that behavior for ifs without then. Is there an easy way I can fix this locally for now?

**Comment by Thom1729** [comment]
The linked PR should fix this.

**Comment by RheingoldRiver** [comment]
Yes, that's perfect, thanks!
