### ISSUE TITLE
Lua - unmatched quotes also error for too long

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#1905]
One more Lua issue, sorry (overall the highlighting is way better than what I was using before with LuaExtended & I love it!) - [Screenshot](https://puu.sh/D0LTQ.png) - In contrast to the same issue occurring in the JS language definition, which only errors the one line with the missing closed quote ([screenshot](https://puu.sh/D0LZ8.png)), an imbalanced quote in Lua causes the rest of the document to be errored. Could this be changed to just the one line, the way JS behaves?

**Comment by michaelblyons** [comment]
Keep posting these bug reports as you find them; they're really helpful. But please also include some example code (as text 😉) in the bug report.

It doesn't have to be your production code. Anything that demonstrates the problem is great. Then, no one has to transcribe or OCR your screenshot to see what you're seeing. Thanks!
