### ISSUE TITLE
[JavaScript] Scopes issue (variable.other.)

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#192]
Same thing has a different scope if its chained method is carried to the next line. Here you can see the `DOM` variable stops being `variable.other.class.js` if its chained method `.select()` is on the next line 

![screen shot 2016-02-20 at 1 14 46 am](https://cloud.githubusercontent.com/assets/679341/13192748/1e6344c6-d778-11e5-8738-b92814533e2a.png)
![screen shot 2016-02-20 at 1 15 35 am](https://cloud.githubusercontent.com/assets/679341/13192750/21f92c90-d778-11e5-87a3-276280dd93fe.png)

**Comment by wbond** [comment]
I'm not sure we can make the second like the first. This is due to two facts:

 1. JavaScript's automatic semicolon insertion
 2. Sublime Text processes text one line at a time

Since semicolons are implicitly inserted according to non-trivial rules and Sublime Text only processes one line at a time, there isn't a way to enter a lexing state for sources.DOM where we can pick up on the next line. Thus we need to process one line at a time, unless we can enter a new state via a `{`, `(` or similar.

That said, I've been working on some heavy refactorings of the JavaScript syntax over the past few days. These fix quite a number of edge cases that were incorrect before and make it faster (around 4x faster). However, in the process, some of the hyper-specific scope information is not maintainable. For instance, `meta.function-call.static.with-arguments.js` no longer exists. Instead:

 - `sources` will be `variable.other.object.js`
 - `DOM` will be `meta.property.object.js`
 - `status()` will be `meta.function-call.method.js variable.function.js`

That said, both segments of code will highlight with the same scopes, so at least you will have consistent colors.

**Comment by wbond** [comment]
As mentioned in the previous comment, this no longer applies to the current refactoring. I did add a test to ensure they are consistent in 412635a10fe39ae507656d6aee7e502180de2505.

**Comment by websash** [comment]
Processing one line at a time won't allow the proper scope for parameters in code like this, right? :(
```javascript
const foo = (value, 
             props) => {
  // ...
}
```

**Comment by wbond** [comment]
That is correct. Unfortunately constructs that require multiple passes or multiple lines of source code currently can not be highlighted properly.

Jon and I have been discussing some ideas on how to handle this, but we don't have anything yet.

**Comment by websash** [comment]
I see, thanks

**Comment by wbond** [comment]
@websash Just a note, such formatting on an arrow function definition is not handled by, other, similar text editors :smile:

**Comment by websash** [comment]
Yeah, you probably need a full-featured js parser for things like this. I was recently playing with Emacs and its js2-mode. They do have it working. There's kind of a parser built-in in that mode
