### ISSUE TITLE
Class fields

### ISSUE THREAD

**Issue by shabakur-mitra** [sublimehq/Packages#1949]
Fix from #1292 doesn't work (/cc @Thom1729)

```js
class MongoDB_Wrapper extends BaseWrapper {
  #data = getDataObject();

  fetchData(params = []) {
    let num = 0;
    for (const param of this.#data.get('value'))
      if (param === null) return -1;
      else num += param.size;
    return num;
  }
}
```

![](https://user-images.githubusercontent.com/50108360/56901957-8ecf4680-6a99-11e9-8a8c-3ecb2717a791.png)

We need fast fix for this. Hope someone can resolve it soon.

**Comment by Thom1729** [comment]
Looks like the private field implementation does not handle private names as dotted properties. I'll fix it.

**Comment by Thom1729** [comment]
Looks like `this.#foo` was never implemented at all, but because of graceful error handling no one noticed. The inside of a `for`/`of` declaration is necessarily a lot less fault-tolerant, so it blew up.

If you need a fix right away, you can download the syntax in the PR into your Packages directory (under `Packages/JavaScript/JavaScript.sublime-syntax`). If you do, just remember to un-patch it eventually.

**Comment by shabakur-mitra** [comment]
Thank you sir
