### ISSUE TITLE
[Ruby] Syntax highlighting with require method

### ISSUE THREAD

**Issue by shaicoleman** [sublimehq/Packages#2000]
require can be sometimes a keyword, and sometimes a method (commonly used with Rails Strong Parameters). It breaks highlighting when used as a method

![image](https://user-images.githubusercontent.com/127225/59916614-9535cb00-9417-11e9-982c-7b1231114e2c.png)

```
class MyParams
  def require(param_name)
    "#{param_name}*"
  end
end

puts 2 + 3
puts "#{MyParams.new.require(:filename)}"
puts 2 + 3
```

**Comment by stuxcrystal** [comment]
Technically, `require` is never a keyword.

`require` is implemented in the module `Kernel`: https://ruby-doc.org/core-2.6.3/Kernel.html#method-i-require

So is the method [`new`](https://ruby-doc.org/core-2.5.3/Class.html#method-i-new) btw.

**Comment by deathaxe** [comment]
The scope used for `new` and `require` is `keyword.other.special-method.ruby`. So these being methods seems to have been known by the original author. Don't know why they are scoped as keyword.

The broken syntax is caused by `require` to push into a context which pops off at the end of a line only.
