### ISSUE TITLE
[C/C++] Syntax highlighting can lose track of scope across macros

### ISSUE THREAD

**Issue by digikata** [sublimehq/Packages#201]
When braces are in macros, the syntax highlighting can lose track of scope, messing up highlighting later in the file.

```
int foo(int val)
{
	int result

	result = func(val);

	if (result == 0) {
		return 0;
#if CROSS_SCOPE_MACRO
	} else if (result > 0) {
		return 1;
#endif
	}
	return -1;
}

/* bar should be function highlighted */
void bar(int foo)
{
}
```
The syntax file in the  [C Improved plugin](https://github.com/abusalimov/SublimeCImproved) seems to handle this ok though I'm not exactly sure it's an easy update to get it into the default syntax file - the C improved syntax file seems to have major differences.

**Comment by wbond** [comment]
Just a heads up, I've been working on combining #28 with some additional changes to get the C and C++ syntaxes to a more robust state. My hope is to have the changes as part of the next dev build.

**Comment by wbond** [comment]
There is a version of the C/C++ rewrite at https://github.com/sublimehq/Packages/tree/c-rewrite if you want to do some testing. To do so, you should check out the c-rewrite branch and follow the directions at https://github.com/sublimehq/Packages#installation.

Just note that Objective C and Objective C++ are broken right now since I need to rewrite them to work with the new C and C++ syntaxes.

**Comment by wbond** [comment]
This should be fixed in master now
