### ISSUE TITLE
[JavaScript, enhancement] scope for the "TODO:" label in comments

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#212]
It would be nice to have one for highlighting todo notes

**Comment by FichteFoll** [comment]
I do believe this to be a plugin's job instead of the grammar's.

I, for example, use SublimeLinter-annotations.

**Comment by websash** [comment]
Didn't know about SublimeLinter-annotations. I've just installed it and, yeah, it highlights the same way as warnings and errors, which I'd say is not that noticeable or distinguishable from my real errors/warnings (same stippled underline style I use).

**Comment by wbond** [comment]
I don't think this currently fits with the existing packages, or what we are trying to accomplish with them via the syntax files.

I think if you are interested in trying to push more for this, a discussion on the forum with some research into the conventions around various language community and if/how they deal with "todo" items incomments.

**Comment by callodacity** [comment]
I would really love this feature in Sublime Text as well, and I've been looking at ways to write a plugin to enable this sort of behaviour, but the only solutions I've found are either through linting (like SublimeLinter-annotations) or through using marked regions (HighlightWords plugin). Neither of which can change the colour of the text, only adding styles to it (underlines, outlines, filled rects, etc). Which, IMO, isn't ideal for clarity and user experience.

One other option could be running a `mini-syntax` of sorts over the current syntax in the view (not sure if this is possible).
If there is a way to run a `mini-syntax` over the current one, we could then write a syntax for highlighting these words in comments that would apply to all syntaxes.

Otherwise, we would have to change every syntax to include them. And from what I can tell from @wbond's comment this is currently undesired. So as it stands, if a user wishes to have this behaviour they would have to maintain a modified copy of every syntax which is somewhat cumbersome!

This is something I immediately loved about the Atom editor when I tried it, and I think it would make a great addition to Sublime Text, however, with the current Plugin API I'm not too sure it's possible to do nicely and cleanly. 

On another note, it does look like this has crept into Sublime Text's syntaxes at some stage:
https://github.com/sublimehq/Packages/blob/d15cd7fb209c5ff7a53f47d1fac235f406f903b5/C%23/C%23.sublime-syntax#L79
