### ISSUE TITLE
[LaTeX] Escaped percentage symbol in D column specifier breaks the highlight

### ISSUE THREAD

**Issue by Shedarshian** [sublimehq/Packages#2238]
- Sublime Version: 3.2.2 Build 3211
- OS Version: Windows 10 Pro Build 1909 edition 18363.535

``` LaTeX
\documentclass{article}
\usepackage{dcolumn}
\begin{document}
\begin{tabular}{c|D{\%}{\%}{-1}}
\hline 1.1\% & 1.2\% \\\hline
2.1\% & 2.22\% \\\hline
\end{tabular}
\end{document}
```
This code can be compiled correctly to:
![image](https://user-images.githubusercontent.com/17756612/71346017-dadb7800-25a1-11ea-80b2-99d26f2136f7.png)

, while the highlight breaks.

![image](https://user-images.githubusercontent.com/17756612/71345956-aff12400-25a1-11ea-8648-0b41e4ba9da9.png)

**Comment by jwortmann** [comment]
The "D{}{}{}" column type is not recognized because it is an addition from the "dcolumn" package. The following would be a simple fix for it and allow escaped characters like `\%` and commands inside of braces in the column specification block after `\begin{tabular}`:
[LaTeX.sublime-syntax#L1608-L1615](https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/LaTeX/LaTeX.sublime-syntax#L1608-L1615)
```diff
@@ -1612,4 +1612,6 @@
         - match: '\}'
           scope: punctuation.definition.group.brace.end.latex
           pop: true
+        - include: general-constants
+        - include: general-commands
         - include: array-preamble
```
I'm not sure about creating a pull request for it though, as I only quickly looked over that syntax file, and it wouldn't be as clean as adding a proper rule for the "D" column type. But I don't know how much stuff from external packages like this should be put into the syntax.
