### ISSUE TITLE
[JavaScript] certain function declarations are not being scoped properly

### ISSUE THREAD

**Issue by MattDMo** [sublimehq/Packages#229]
I apologize for not using the correct terminology, as I'm not a JavaScript guy. As far as I can tell, there are two ways of defining named functions in JavaScript:
```js
function foo() {
    // do stuff
}
```
and
```js
bar: function() {
    // do other stuff
}
```
However, it also seems that one can use the second construct to assign arbitrary values to variables:
```js
baz: "some text"
qux: {
    a: b,
    c: d
}
```
In the current iteration of `JavaScript.sublime-syntax`, when using the top method to define a function, the function's name (`foo`, in this case) is scoped as `meta.function.declaration.js entity.name.function.js`. In JavaScriptNext, in the second form, the function name (`bar`) is scoped as `meta.function.json.js entity.name.function.js`, whereas `baz`, `qux`, `a`, and `b` are scoped as `constant.other.object.key.js string.unquoted.label.js`, allowing for them to be differentiated by a color scheme. However, `JavaScript.sublime-syntax` scopes all of them (`bar`, `baz`, `qux`, `a`, and `b`) as `entity.name.label.js`, with no differentiation between the function name and regular keys.

The new `.sublime-syntax` file is huge, and I haven't even attempted to find where the issue might be, let alone try to fix it, so this is just an issue for now. If someone who is better acquainted with the syntax definition could solve this, that would be great.

**Comment by wbond** [comment]
I just checked this out.

If you are seeing `entity.name.label`, that indicates that you are missing commas in your object literal.

For instance, in the following:

```js
function foo() {
    // do stuff
}

var a = {
    bar: function() {
        // do other stuff
    },
    baz: "some text",
    qux: {
        a: b,
        c: d
    }
}
```

`bar`, `baz, `qux`, `a` and `b` all get the scope `meta.object-literal.key`. `foo` and `bar` get `entity.name.function`.

If you remove the commas in the object literal, `qux` will get scoped as a label instead of a key. I should be able to tweak it so this incorrect syntax is still parsed semi-reasonably.

```js
function foo() {
    // do stuff
}

var a = {
    bar: function() {
        // do other stuff
    }
    baz: "some text"
    qux: {
        a: b,
        c: d
    }
}
```

**Comment by MattDMo** [comment]
OK, I see. I did a little googling with your terminology, and here's what I think happens: A **[label](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label)** is used as an identifier for a statement, like a `for` loop, and can be used later to refer to that statement. It can occur anywhere in the code. Multiple labels do not need to be separated by commas. Am I also correct in saying that a label cannot be applied to an otherwise anonymous function?

On the other hand, a **key** can only be used within an object literal. Its value can be any other JS object, such as a variable, string, function, array, etc. Multiple key: value pairs must be separated by commas, just like in JSON.

So if all of this is the case, then my original `bar` code was incorrect if it was outside the scope of an object?

**Comment by wbond** [comment]
Correct, `my_identifier:` outside of an object literal is a label, which is used with `continue` or `break` for loop control. In other languages that support `goto`, it would be used for that also. It is not a variable.

Yes, if your syntax consisted of just `bar: function(){}`, that doesn't really make sense. If it was `var obj = {bar:function() {}}`, then you have a valid construct.

Note that object literals have to be passed to a function or assigned to a variable. Otherwise the syntax `{}` signifies an anonymous block in JavaScript.

I will leave this issue open so I can ensure that in the context of an object literal, that if a comma is omitted, a `my_identifier:` will still be scoped as an object key, and not a label.

**Comment by wbond** [comment]
df8cff8745121affba35456d099af75798717b7c improves the grammar to prevent parsing semi-broken object keys as labels.
