### ISSUE TITLE
[Python] comment scope inside triple-quoted-string

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#2365]
- Sublime Version: 4074

The following fails, but should not
```python
x=r'''x#y
#      ^^ - comment
#x
# <- - comment
#^ - comment
'''
```
Everything inside the triple quotes is in fact part of the string:
```
>>> x=r'''x#y
#      ^^ - comment
#x
# <- - comment
#^ - comment
'''

>>> x
'x#y\n#      ^^ - comment\n#x\n# <- - comment\n#^ - comment\n'
```

**Comment by FichteFoll** [comment]
What you're seeing are comments within an extended regular expression. Because extended mode can be enabled through a flag to `re.*` calls, we use some arbitrary heuristic to determine whether extended mode is enabled or not by looking for a quotation character in the rest of the (potentially commented) line.

**Comment by rwols** [comment]
This seems like a fair trade-off. If I remove the `r` I get the correct highlighting.

**Comment by FichteFoll** [comment]
You can use upper-case `R` to have a raw string without regex highlighting.
