### ISSUE TITLE
[C++] Override specifier not highlighted in ctor/dtor

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#237]
'override' specifier is not highlighted in both constructor and destructor. It is highlighted in Method().

The highlighted override has scope `storage.modifier.c` (amongst others).

```
class Foo : public Bar {
 public:
  Foo() override;
  ~Foo() override;

 void Method() override;
};
```

**Comment by wbond** [comment]
Just a heads up, I've been working on #28 and additional tweaks to C and C++. My hope is to have them in the next dev build.

**Comment by wbond** [comment]
There is a version of the C/C++ rewrite at https://github.com/sublimehq/Packages/tree/c-rewrite if you want to do some testing. To do so, you should check out the c-rewrite branch and follow the directions at https://github.com/sublimehq/Packages#installation.

Just note that Objective C and Objective C++ are broken right now since I need to rewrite them to work with the new C and C++ syntaxes.

**Comment by wbond** [comment]
This should be fixed in master now
