### ISSUE TITLE
[Erlang] Variables, modules, record names and fields are indistinguishable

### ISSUE THREAD

**Issue by eproxus** [sublimehq/Packages#2372]
- Sublime Version: 4074
- OS Version: macOS 10.15.4
``` erl
#foo{foo = Foo} = bar:baz()
%^ variable.other.record.erlang
%    ^ variable.other.field.erlang
%          ^ variable.other.erlang
%                 ^ variable.namespace.erlang
```

Everything is prefixed with `variable.` which makes color schemes highlight everything in the same color. In Erlang records, record fields and modules are not "variables".

<img width="496" alt="Screenshot 2020-05-27 at 18 20 47" src="https://user-images.githubusercontent.com/112878/83046092-cadf2d00-a046-11ea-8a59-1202a5e9c1f4.png">

(Monokai color scheme on [meck_proc.erl](https://github.com/eproxus/meck/blob/master/src/meck_proc.erl#L212-L244))

**Comment by eproxus** [comment]
Ping @deathaxe

**Comment by deathaxe** [comment]
With regards to https://www.sublimetext.com/docs/3/scope_naming.html, what top-level scope would you choose for `records`, `fields` and `modules`?

I know Erlang has the concept of `atom`s vs. `variables`. But that's not covered by any specification atm.

The `variable` top-level scope is generally used for user defined `identifiers`. Function identfiers use `variable.function` for instance. A `field` would normally need to be scoped `variable.other.member`, but I chose `variable.other.field` as it felt more suitable for Erlang. Maybe we should change that. A record in general may be compared to C's `struct`? Thus it's identifier is nothing else than a `variable` even though I am not sure whether this assumption is perfect with regards to the usage in Erlang.

Some legacy syntaxes use `support.class`, `support.namespace` or even `support.type.class` ... for `modules` but `support` is reserved for elements of standard libraries. Thus `variable.namespace` feels as the best common alternative for user defined `modules` or those not supplied with OTP (or those we can't match for some reason). Here's the related jet open RFC discussion https://github.com/sublimehq/Packages/issues/1842. 

That said, the main goal is to define semantically acceptable/correct consistent general purpose scope names, which can be used by color schemes to provide a consistent UX for as many syntaxes as possible with minimal effort. We do not want to hack scope names to match certain color schemes as it fails with most of them anyway.

I'd be fine to modify scopes which fulfill that requirement.

Otherwise 
a) the color scheme might propably need some tweaks to address the new scopes, which does not only apply to `variables` scopes in Erlang, maybe.
b) the existing scope names should be sufficient enough to define user defined overrides if existing colorization is not enough.

Here's my look with a slightly modified _Brackets Dark_

![grafik](https://user-images.githubusercontent.com/16542113/83052926-45607a80-a050-11ea-85ab-82099b1d3843.png)

Just added

```
        {
            "scope": "variable.namespace",
            "foreground": "var(purple)",
        },
        {
            "scope": "variable.other.record",
            "foreground": "var(blue)",
        },
        {
            "scope": "meta.atom variable.other",
            "foreground": "var(orange)",
        },
```

... next to some other tweaks to properly highlight operators and punctuations.

**Comment by eproxus** [comment]
If the `variable.` prefix is used for almost everything in most other syntaxes, I would say we should keep it that way. Perhaps there are more general names under than namespace that we can use?

For example, I think using `variable.other.member` for record fields is more appropriate, because it will most probably result in the most appropriate colouring. That being said, the default Monokai scheme shipping with sublime groups `entity.name` etc. along with `variable.other.member`. Not sure that is "correct" (otherwise, what's the point of having two different namespaces?).

The downside with the current scope naming conventions is that they have an object oriented heritage. That can be seen in the `variable.function` scope for example, which I assume is intended to be used in a `ObjectInstance.my_function()` fashion.

The problem with Erlang is that ideally the following would be coloured distinctly:
* Atoms: already covered by `constant.other`
* Functions: already covered by `variable.function`
* Modules: not sure what would fit here. Python, for example, doesn't even set a scope for modules used in the code... (maybe we should use `variable.other.constant`?)
* Variables: already covered by `variable.other` (perhaps should be `variable.other.readwrite`?)
* Records and their fields: fields can be covered by `variable.other.member` but what about records?

**Comment by deathaxe** [comment]
> what's the point of having two different namespaces?

With regards to functions:
- the name in a definition statement is scoped `entity.name.function`
- the name in a function call uses `variable.function`

The original scope names come from TextMate. When studying its naming guidelines and comparing different syntaxes, I found many missing details and different solutions for compareable statements. Maybe because things moving forward?

It looks like `entity.name` is used for definitions and `variable.` for references in some cases. There are still inconsitencies about that in different syntaxes, but maybe that's a strategy, which can help to distinguish definitions and references easily. ST4's indexer seems to rely on `entity.name` to specify a symbol's kind for instance.

> Perhaps there are more general names under than namespace that we can use?

You mean instead of `variable.namespace`?

What's more general? ST's scope naming guidelines suggest this scope for namespaces, modules, packages, etc. which all do nothing else than create certain lookup areas to avoid duplicated or insanely named functions. OK, the name itself is a bit C-style and may be a compromise for syntaxes which group functions/variables via modules or packages, but is there such a big difference semantically?

I'd keep the `variable.namespace` for modules. We already moved a couple of syntaxes to it.

> Variables: already covered by `variable.other` (perhaps should be `variable.other.readwrite`?)

Reasonable.

> Records and their fields: fields can be covered by `variable.other.member` but what about records?

I'll change the field scopes.

Some general notes about records:

In a record definition clause (`-record(name, {field=value, ...})`), `name` and `field` are scoped as `entity.name` while they are `variable. ...` in the `#record{field=value}` statement.

I am not quite sure about the real meaning of `#record`. Is it a local definition of a record? Then we could propably also use `entity.name.record`. I read it as some kind of expression to return certain fields of a record to the caller, thus understood it as a reference of an existing record. What do you think?

**Comment by eproxus** [comment]
I agree about stickting to conventions. 👍

Could a possibility for module name scopes be `variable.other.constant.erlang.module` and normal variables thus be `variable.other.readwrite`?

> I am not quite sure about the real meaning of #record. Is it a local definition of a record? Then we could propably also use entity.name.record. I read it as some kind of expression to return certain fields of a record to the caller, thus understood it as a reference of an existing record. What do you think?

Records are like named structs. So `#foo{}` means create a new record of the type `foo`. Then in patterns it of course means match against the record type `foo` and any internal field patters, e.g. `#foo{bar = 1} = MyRecord`. The record is implicitly "created" there, but never "used" so to speak.

Question is what scope to use for record. You don't want the `entity.` name space if that will make Sublime index _every_ use of the record all throughout the code.

**Comment by eproxus** [comment]
Actually, looking through the suggestions for various `variable.` scopes in the documentation you linked, there's simply not enough sub types to cover all of Erlang.

**Comment by eproxus** [comment]
I like your suggestions a lot. I think using the same scopes as class instantiations for Java makes sense, perhaps also coupled with the same scopes for class definitions when records are defined (`-record(...)`)?

It makes sense to add the language scope at the end, of course. In my observation almost no color schemes actually makes use of these, except for very common languages, so therefore I wanted to make the top level scopes more expressive if possible.

If what you propose under `entity` and `variable` would take off, I assume that would mean a large refactoring of many syntax definitions and themes in Sublime?

**Comment by deathaxe** [comment]
> almost no color schemes actually makes use of these

That's the main reason to place the language scope to the end. A color scheme shouldn't need to be forced to use syntax specific rules. In a perfect world it would only need at most 3 levels of subscopes to address all required tokens.

> ... I assume that would mean a large refactoring of many syntax definitions

I guess many syntaxes could profit from the latest ST4 branching features and therefore would need some attention anyway.

With regards to `namespaces` etc. there is currently no real common solution. Each syntax seems to use different scopes for nearly the same thing. The hope was just to find one scope which can be used everywhere.

In a more general manner it may result in a bit more work. But I guess the entity vs. variable scheme can't be applied to all syntaxes in all situations anyway. In python for instance, the static lexer can't know about which variable is the declaration (first usage) or which ones are references only.

It more or less suggests to use those when possible or appropriate to help driving the _Goto Definition_ vs. _Goto Reference_ features in a consistent way.
