### ISSUE TITLE
[Bash] Comment after redirection make next line wrong scope

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#2391]
```bash
foo > ${bar} # comment
if [ $? -eq 0 ]; then
    # comment
fi
```

![image](https://user-images.githubusercontent.com/6594915/85464962-d5a3c800-b5da-11ea-924d-4fcf1a044aaa.png)
See the `if` and the condition.

## References

- https://www.reddit.com/r/SublimeText/comments/heauml/if_not_recognized_as_a_keyword_if_and_in_the/

**Comment by michaelblyons** [comment]
Also at https://forum.sublimetext.com/t/color-bug-in-shell/51820

**Comment by jfcherng** [comment]
```diff
diff --git a/ShellScript/Bash.sublime-syntax b/ShellScript/Bash.sublime-syntax
index e973e319..106bb8a8 100644
--- a/ShellScript/Bash.sublime-syntax
+++ b/ShellScript/Bash.sublime-syntax
@@ -540,16 +540,17 @@ contexts:
   redirection-post:
     - match: \s*(?:(\d+)|(-))
       captures:
         1: constant.numeric.integer.decimal.file-descriptor.shell
         2: punctuation.terminator.file-descriptor.shell
       pop: true
     - match: \s*(?=\S)
       set:
+        - meta_include_prototype: false
         - match: (?={{metachar}}|`)
           pop: true
         - include: expansion-and-string
     - match: \s*
       pop: true
```

As mentioned in https://forum.sublimetext.com/t/color-bug-in-shell/51820/9, the above diff fixes this particular case (i.e., `comment` after `redirection`). @deathaxe seems to work on a better solution (as mentioned in https://forum.sublimetext.com/t/color-bug-in-shell/51820/10).

**Comment by deathaxe** [comment]
Should be fixed by https://github.com/deathaxe/sublime-packages/tree/pr/shellscript/patchset-2020

I'll open a pull request once the other PRs are merged and it becomes clear which of the open syntax related core issues are fixed as some of the changes in that branch may interfere with possible core changes.

The whole handling of comments is not optimal for several reasons. Fixing those issues required a couple of design changes. So the patchset-2020 will become a somewhat bigger PR.
