### ISSUE TITLE
[TypeScript] Fails to highlight arrow function with types

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2468]
- Sublime Version: 4084

There are some failures with highlighting this code.

```ts
const merge = (target: JSONSchema, sourceRoot: JSONSchema, sourceURI: string, refSegment: string | undefined): void => {
	const path = refSegment ? decodeURIComponent(refSegment) : undefined;
	const section = findSection(sourceRoot, path);
	if (section) {
		for (const key in section) {
			if (section.hasOwnProperty(key) && !target.hasOwnProperty(key)) {
				(<any>target)[key] = section[key];
			}
		}
	} else {
		resolveErrors.push(localize('json.schema.invalidref', '$ref \'{0}\' in \'{1}\' can not be resolved.', path, sourceURI));
	}
};
```

![Screenshot 2020-08-26 at 23 07 50](https://user-images.githubusercontent.com/153197/91357084-f82baa80-e7f0-11ea-9aa6-a511c8194c46.png)

This is extracted from this file and line: https://github.com/microsoft/vscode-json-languageservice/blob/76f4b43d475f67fd58c6bd2eaea1b0cd01826f84/src/services/jsonSchemaService.ts#L423

**Comment by michaelblyons** [comment]
Works if you remove `: void`. Missing type hint after function assignment?

I'm not too surprised no one had encountered this before. I imagine most people would write

``` ts
function merge (...) : void {
   ...
}
```

**Comment by rchl** [comment]
Pink @Thom1729 :)

**Comment by Thom1729** [comment]
FYI, I'm looking at this, and I hope to have a proper solution soon. This is probably the trickiest thing to get right with TypeScript because of situations like this:

```ts
x ? (y) : z;
x ? (y) : T => r : z;
```

**Comment by rchl** [comment]
For good measure here is a slightly different case but probably the same issue: https://github.com/Anidetrix/rollup-plugin-styles/blob/7532971ed8e0a62206c970f336efaf1bcf5c3315/src/loaders/postcss/url/index.ts#L59-L192

The two ending braces of that block are rendered in red.

**Comment by deathaxe** [comment]
Here's another failing example:

```tsx
function bloadware() {

    return (
        <ul type="cards">
        { 
            list.map((item: Faq)) => (

                <li
                    class={item.class}
                >
                    {item.text}
                </li>
            ) 
        };
        </ul>
    );
};
```

**Comment by Thom1729** [comment]
That example has a typo:

```
list.map((item: Faq)) =>
```

The above has an extra close paren. It should be:

```
list.map((item: Faq) =>
```

There's still something wrong with the argument list parsing, though.

**Comment by Thom1729** [comment]
@deathaxe Actually, I'm looking at it now and the fixed example works fine. Perhaps this was fixed in the latest build?

(The original issue still needs work.)

**Comment by deathaxe** [comment]
I actually tried to find a minimal example to reproduce https://github.com/sublimehq/sublime_text/issues/3656#issuecomment-699958100 which was reported to occur with ST 4087.

**Comment by wbond** [comment]
@Thom1729 Is this something you are actively working on, or would it be fine for me to take a stab at it?

**Comment by Thom1729** [comment]
Feel free. I'm experimenting with various approaches, but I haven't quite hit upon the right one yet. I think the bug you posted on Discord (`if (a < b || c < d) {}`) is key — type expression parsing is going to have to be exact so that invalid type expressions will fail their branches.

**Comment by Thom1729** [comment]
@wbond Come to think of it, https://github.com/sublimehq/sublime_text/issues/3494 might be relevant here.

Most of the time, we want type expressions to be parsed pretty loosely so that the highlighting won't go nuts when the user is typing. In `expression-begin`, if we see a token we don't expect, we pop back to `expression-end`. But if we're on the `ts-function-type-arguments` branch, this should cause it to fail. I've fixed the `a < b || c < d` problem just by replacing `include: else-pop` in `expression-begin` with a rule that also fails `ts-function-type-arguments`. (I haven't done a detailed analysis of other possible failure points, but I expect that this solution should work in principle.)

A similar approach should work for arrow function return arguments. Any unexpected token could fail the appropriate branch point. The catch is that we can't re-use the `ts-function-type-arguments` branch point in another rule and we can't fail two branch points in a single rule. We could get around that by duplicating all of the type expression contexts, but that would be a *lot* of copy-pasted code.

**Comment by rchl** [comment]
This is fixed now.
