### ISSUE TITLE
[C++] Scope overflow involving functions and macros

### ISSUE THREAD

**Issue by LoneBoco** [sublimehq/Packages#258]
First, look at this code:
```c++
int FunctionName(
				INPUTMACRO(int, test1),
				INPUTMACRO(int, test2),
				INPUTMACRO(int, test3)
			)
{
	int somestuff;
	return 1;
}

int FunctionName(
				INPUTMACRO(int, test1),
				INPUTMACRO(int, test2),
				INPUTMACRO(int, test3)
			)
{
	int somestuff;
	return 1;
}
```
The scope of the "int somestuff" in the second function is as follows:
```
source.c++
meta.function.c
meta.parens.c
meta.function.c
meta.parens.c
meta.function.c
meta.block.c
```
It is detecting the macros as a function (that's fine) and not properly popping them from the stack (not fine).  This is most likely related to #149.  What happens is that after a couple of these, syntax highlighting starts to break further down in the file.

**Comment by wbond** [comment]
I've been working on the C and C++ syntaxes, and my hope is to have them significantly improved in the next dev build through a combination of #28 and work I am doing right now.

**Comment by wbond** [comment]
There is a version of the C rewrite at https://github.com/sublimehq/Packages/tree/c-rewrite if you want to do some testing. To do so, you should check out the `c-rewrite` branch and follow the directions at https://github.com/sublimehq/Packages#installation.

Just note that Objective C and Objective C++ are broken right now since I need to rewrite them to work with the new C and C++ syntaxes.

**Comment by LoneBoco** [comment]
The scope overflow is gone in the c-rewrite branch.  Syntax highlighting worked the entire way through my file.

**Comment by wbond** [comment]
This should be fixed in master now
