### ISSUE TITLE
[Markdown] list punctuation

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#264]
ST build 3019

List items in Markdown only appear to have the punctuation scope defined for the first item in a list.

e.g.

```
# Title

- unordered list item
- another list item
  - subitem

1. numbered list item
2. another one
```

![markdown list punctuation](https://cloud.githubusercontent.com/assets/11882719/14149284/21a46a9a-f6ac-11e5-8863-b4faf7b46b07.png)

I would expect all the `-` and `.` characters to be highlighted in this example.

scope at the first `-` is: `text.html.markdown markup.list.unnumbered.markdown punctuation.definition.list_item.markdown`
scope at the second `-` is: `text.html.markdown markup.list.unnumbered.markdown meta.paragraph.list.markdown`

ideally, some syntax tests would be created as part of this package.

**Comment by aziz** [comment]
This has been fixed by some external packages like my [PlainNotes](https://github.com/aziz/PlainNotes) or [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing) but the built-in Markdown package still has a lot of issues that has not yet been addressed. 
I personally hope, markdown syntax gets some love in the near future.

**Comment by wbond** [comment]
@aziz If you can create issues for the problems you know of, and include example content, I will work on getting it fixed up!
