### ISSUE TITLE
[Haskell] Syntax Highlighting problem

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#2670]
Perfectly valid Haskell code:

```
(--)'ab'(
  main)=putStr"ok"
```

![](https://user-images.githubusercontent.com/73323009/102899419-2487c880-446b-11eb-9640-b3f114fcba1f.png)

**Comment by deathaxe** [comment]
I am not a Haskell expert, not even a beginner, but according to the first answer at https://stackoverflow.com/questions/22913292/single-vs-double-quotes-in-haskell this is not valid code.

> In Haskell, `'c'` is a single character (`Char`), and `"c"` is a list of characters (`[Char]`).

That's also what I read from http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html

**Comment by SlavKing98** [comment]
@deathaxe You are missing the point. The code is equivalent to `(main)=putStr"ok"` because `--)'ab'(` is just a comment. There are no character literals in the code. You can [try it online](https://tio.run/##y0gszk7Nyfn/X0NXV1M9MUldg0tBITcxM0/TtqC0JLikSCk/W@n/fwA) and confirm yourself that it prints "ok" properly.

**Comment by deathaxe** [comment]
Is it a challence of a fetish to look for such kind of absurd absolutely none-real-world constructs to try to break things?

What I mean, who would write such kind of comment in real code - not that it wouldn't be fixable.
