### ISSUE TITLE
[Bash] Auto-pair interpolations even in a string context

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#2677]
- Sublime Version: 4094
- OS Version: macOS 11.1

## Expected behavior

`|` denotes the caret. When typing a `{` in

```
foo="$|"
```

I would expect an auto-pairing keybinding to trigger and complete it to

```
foo="${|}"
```

## Actual behavior

ST ignores auto-pairing of curly brackets inside strings and we end up with

```
foo="${|"
```

Note that the auto-pairing of curly-brackets and parentheses works as intended when not in a string context.

Because the bash syntax is fairly good these days, I would expect such a key-binding to make use of

- `meta.interpolation.parameter` or,
- `punctuation.section.interpolation.begin`.

From what I understand the `"selector"` key of a keybinding context checks the scope *to the right* (?) of the caret, making `punctuation.section.interpolation.begin` useless for this.

**Comment by deathaxe** [comment]
That's a quite common issue which seems to apply to several syntaxes in the one or the other way. Such a thing is requested in https://github.com/sublimehq/sublime_text/issues/3829.

What I'd like to know is, whether we want to or can find some common patterns which might be implemented in global key bindings or whether we want to add specific key bindings for each syntax.

Pairing brackets within strings doesn't feel to odd to me. Maybe we can implement global keybindings for such special use cases which can be enabled/disabled via syntax specific settings then, rather than add the same binding for each syntax.

**Comment by rwols** [comment]
What I'm also noticing is that these tight `punctuation` scopes are unfortunately not usable for the same reason that `punctuation.accessor` was not usable in (older?) ST3 builds: the `"selector"` context for a key binding checks the scope *to the right* of the caret. The auto-complete selector also *used* to do the selector check *to the right* of the caret. But this was changed in ST4 (or a late ST3 build, can't remember), where the auto-complete selector now does the check *to the left* of the caret, making the `punctuation.accessor` scopes super useful.
