### ISSUE TITLE
Color is not getting changed

### ISSUE THREAD

**Issue by Mosaib** [sublimehq/Packages#2681]
:root{
--svdeepblue:#010a51;
--svlightblue:#0213a1;
--svmainyellow:#feca07;
--svlightyellow:#b99408;
--svwhite:#fff;
}

background-image: linear-gradient(var(--svlightblue) , var(--svlightyellow));

Color of Code is not getting changed while coding in Cascading style sheet.

![color changed github](https://user-images.githubusercontent.com/54113943/103457073-10bd4b80-4d22-11eb-981e-c93ce1af48ca.png)

**Comment by deathaxe** [comment]
The issue was `var()` not being supported in various value contexts, which has been fixed by PR #2556. Here's how it looks with ST4094.

![grafik](https://user-images.githubusercontent.com/16542113/103457281-1ef97080-4cfe-11eb-8696-b6f1bea41ccf.png)

**Notes:**

1. CSS.sublime-syntax is no longer compatible with ST3.
2. `background-image` and `linear-gradient` using the same color is an issue of Monokai color scheme. The syntax definition correctly applies different scopes to those tokens.

   Here is what it looks like with my modified Brackets Color Scheme.
   ![grafik](https://user-images.githubusercontent.com/16542113/103457367-ff167c80-4cfe-11eb-9b73-827c06960695.png)

**Comment by wbond** [comment]
This appears to be fixed in our latest version of the CSS syntax, so I am closing
