### ISSUE TITLE
[CSS] Subword navigation not working with dash in names

### ISSUE THREAD

**Issue by dubeg** [sublimehq/Packages#2709]
- Sublime Version: 4096
- OS Version: Windows build 19042.746

## Expected behavior
Subword navigation should stop at dashes in the middle of class names, property names, etc.

## Actual behavior
It skips dashes. It works with camelCase however.

Subword nav works with dashes in HTML files, so I'm guessing it's specific to the syntax definition of CSS. Am I wrong?

**Comment by michaelblyons** [comment]
Funny how something isn't noticed, and then everyone talks about it at once. This is caused by two things working together:

-  One is the `CSS.sublime-settings`&rsquo; [removal of `-` from `word_separators`](https://github.com/sublimehq/Packages/blob/master/CSS/CSS.sublime-settings#L9-L10) (which you can override).
- The other is [a core issue](https://github.com/sublimehq/sublime_text/issues/3908) where `-` should be a stop-word for subwords, but was probably missed because it's usually part of `word_separators`.

**Comment by dubeg** [comment]
@michaelblyons Ah, that's what it is, thank you.
I like the core issue fix better than adding '-' to word_sep if it means that word nav will skip the dash, but subword nav won't. :s

**Comment by deathaxe** [comment]
Related with https://github.com/sublimehq/sublime_text/issues/4100 and https://github.com/sublimehq/sublime_text/issues/3908
