### ISSUE TITLE
[PHP] (Windows) Error loading syntax file XXX: Error in regex: invalid backref number/name in regex (?=^\s*\2\b)

### ISSUE THREAD

**Issue by blackjyn** [sublimehq/Packages#2735]
- Sublime Version: 3211
- OS Version: Windows 8.1 x64

![php8sublimeTextErr](https://user-images.githubusercontent.com/6046191/109959306-dec46780-7d19-11eb-9194-f2bae66e1b39.png)

**Comment by deathaxe** [comment]
The only lines containing this patterns are:

https://github.com/sublimehq/Packages/blob/5554fd25bcd43f642fa998a9f722f2cd43a6a254/PHP/PHP%20Source.sublime-syntax#L1296-L1303

The error message indicates PHP to be embedded in another syntax by using `with_prototype`. This might inject code into the context in question, which might break backref implementation.

**Comment by blackjyn** [comment]
and.... the solution?

**Comment by deathaxe** [comment]
I can't reproduce the issue with a clean ST3211 on Windows, neither by opening a PHP file nor creating a Markdown file with PHP code block.

With the information available the comment states the only possible root cause for the error dialog, while it is still a bit unclear to me, why it triggers on PHP.sublime-syntax directly. If the assumption is correct, the only solution is to avoid those 3rd-party syntaxes, as `with_prototype` injects its context everywhere without a possibility to prevent that.

Such a syntax might be rewritten to inherit from PHP in order to inject its patterns in a more sane way, but this feature is available for ST4 only and may need some advanced engineering work as 
1. PHP is not prepared to be extended this way. 
2. PHP is already a sophisticated mix of PHP Source/HTML/CSS/JavaScript.

To narrow it down, you might provide a list of Packages, you use and an example for the file it triggers for - if so. I guess the dialog shows up for all files?

**Comment by blackjyn** [comment]
This is my other pkgs related to PHP
![php8sublimeTextErr-otherPKGs](https://user-images.githubusercontent.com/6046191/110209992-153ce680-7ec2-11eb-9953-330b255b53df.png)

**Comment by blackjyn** [comment]
I can confirm the dialog triggers on *.php and *.md file only

**Comment by jfcherng** [comment]
Those two packages does nothing to syntax files. The fuzzy searching won't search plugin descriptions. So if there is no sensitive data in the plugin list, then to save people's time (and your time), provide the whole list.

**Comment by blackjyn** [comment]
this 
![dis](https://user-images.githubusercontent.com/6046191/110210440-4e765600-7ec4-11eb-8907-d62b1bbb1ccf.png)

I also tried to use fresh state, but the dialog still occurs

**Comment by jfcherng** [comment]
> this

It's up to the plugin author whether he/she wants his/her plugin shows here. So, just do what I said. `Preferences -> Package Settings -> Package Control -> Settings`

> I also tried to use fresh state, but the dialog still occurs

You mean use have done steps listed in https://www.sublimetext.com/docs/3/revert.html ?

**Comment by blackjyn** [comment]
> You mean use have done steps listed in https://www.sublimetext.com/docs/3/revert.html ?

yep

dis
![dis](https://user-images.githubusercontent.com/6046191/110210818-035d4280-7ec6-11eb-8d20-856390a449af.png)

**Comment by jfcherng** [comment]
Could you also provide the output of `view.settings().get('syntax')` executed from the console (ctrl+\`)?

**Comment by blackjyn** [comment]
> Could you also provide the output of `view.settings().get('syntax')` executed from the console (ctrl+`)?

![sbtext view setting](https://user-images.githubusercontent.com/6046191/110211706-6e107d00-7eca-11eb-9b7d-807b2e449960.png)

**Comment by deathaxe** [comment]
I still can't reproduce with ST3211 x64 on Windows 10 2004 x64, even with all those plugins installed. 

Maybe it is a core issue related to a special code path for Windows 8 ?!

**Comment by blackjyn** [comment]
> A new portable build of ST would be fresh for laziness. https://download.sublimetext.com/Sublime%20Text%20Build%203211%20x64.zip

unfortunately, even with blank fresh portable version doesn't even work either:
![phpsulimteportErr](https://user-images.githubusercontent.com/6046191/110212538-5935e880-7ece-11eb-941a-f40a0c859954.png)

**Comment by michaelblyons** [comment]
Can you comment out parts of your PHP until you find a minimal reproducible example? It sounds like one of your `<<<` constructs is set up in a way that wasn't anticipated.

**Comment by blackjyn** [comment]
> Can you comment out parts of your PHP until you find a minimal reproducible example? It sounds like one of your `<<<` constructs is set up in a way that wasn't anticipated.

Even with blank PHP source code , error occurs : 
![phpsberrbank](https://user-images.githubusercontent.com/6046191/110232673-ac04b400-7f51-11eb-891a-91bcd30ede06.png)

**Comment by deathaxe** [comment]
The error box indicates syntax compilation fails, yes. That's independent from file content.

As I can't reproduce with exactly the same portable zip file on Windows 10, it must be a core bug in a code path for your specific OS.

If you have a license you may try whether it works with ST4 beta build, which can be found at [Discord](https://discord.gg/HcmwdVK). Otherwise we'd need to wait for core devs to have a look into that issue. I guess it's nothing which can be fixed by the syntax definition itself.

**Comment by blackjyn** [comment]
Thank you guys for your patience ! :+1: 
Will wait instead.

**Comment by blackjyn** [comment]
Hello, this issue has been fixed likely.
I'm on Windows x64 with Sublime Text 4 build 4107.
fork and update the repo and ran this
`cmd /c mklink /J "$env:APPDATA/Sublime Text 3/Packages/PHP" (convert-path ./Packages/PHP)`

and the problem I have had experienced above now has gone :D

**Comment by blackjyn** [comment]
Hello, this issue has been fixed likely.
I'm on Windows x64 with Sublime Text 4 build 4107.
fork and update the repo and ran this
`cmd /c mklink /J "$env:APPDATA/Sublime Text 3/Packages/PHP" (convert-path ./Packages/PHP)`

and the problem I have had experienced above now has gone :D
