### ISSUE TITLE
[PHP] Apparent performance problems

### ISSUE THREAD

**Issue by BenjaminSchaaf** [sublimehq/Packages#2829]
Multiple people are reporting performance problems with PHP specifically: https://forum.sublimetext.com/t/st4-slow-after-upgrade-from-st3/57633/3.

Not entirely clear whether this is a core or packages issue, but I think here is a good starting point.

- Sublime Version: 4106

**Comment by jfcherng** [comment]
syntax cache size on my machine:

![image](https://user-images.githubusercontent.com/6594915/119295151-b13bea00-bc88-11eb-9fdc-34f9465b4b0c.png)

**Comment by PapayaMedia** [comment]
> Not entirely clear whether this is a core or packages issue, but I think here is a good starting point.

I guess it is a core issue because it happens even in safe mode.

I was thinking that if this is happening just to load the PHP syntax when the first PHP file is loaded, then there should be an option like "syntaxes_to_preload", and there you could add those you normally use.

In my case, 99% of the files I open are PHP or JS code, then I could add something like this to settings:

`syntaxes_to_preload: [php, js]`

And when I reach the first PHP file, there is a big chance that the syntax is already prealoaded and the file opens immediately, like in ST3.

**Comment by BenjaminSchaaf** [comment]
> I guess it is a core issue because it happens even in safe mode.

`packages` in this context refers to the default packages (this repository). Those are used in safe mode and provide things like PHP syntax highlighting. This very well could just be a problem with the PHP syntax.

**Comment by PapayaMedia** [comment]
Uh oh... I was thinking on Package Control. Thank you for the clarification.

**Comment by FichteFoll** [comment]
For the record, with https://github.com/sublimehq/Packages/pull/2789 I have the following cache sizes and loading a php file from a cold cache (i.e. folder cleared and after a restart) takes ~3s on my machine.

```
~/.cache/sublime-text/Cache/PHP ▶ ll
.rw-r--r--  28k fichte 25 May  0:35 CSS (for PHP).sublime-syntax.cache
.rw-r--r--  10M fichte 25 May  0:36 CSS (for PHP).sublime-syntax.rcache
.rw-r--r--  20k fichte 25 May  0:35 JavaScript (for PHP).sublime-syntax.cache
.rw-r--r-- 9.4M fichte 25 May  0:36 JavaScript (for PHP).sublime-syntax.rcache
.rw-r--r-- 8.9k fichte 25 May  0:35 PHP.sublime-syntax.cache
.rw-r--r-- 9.2M fichte 25 May  0:36 PHP.sublime-syntax.rcache
.rw-r--r--  48k fichte 25 May  0:35 PHP Source.sublime-syntax.cache
.rw-r--r-- 9.1M fichte 25 May  0:36 PHP Source.sublime-syntax.rcache
.rw-r--r-- 1.7k fichte 25 May  0:35 Regular Expressions (PHP).sublime-syntax.cache
```

**Comment by FichteFoll** [comment]
I did some more experiments with the issue. There are a couple `with_protoype` pushes for heredocs with Php interpolation (6 in total). Removing those reduces cache sizes and load times by half.

**Comment by FichteFoll** [comment]
Comparing runtimes with `master` and `st3` branches on my 4106 yielded very comparable results in both file size and initial load time. 

#2789 is a bit slower even (about 50%) because it introduces another level of indirection with PHP interpolation inside JS and CSS strings which wasn't there before.

**Comment by jfcherng** [comment]
In my test, the large cache size comes from

- Those `with_prototype`s in order to support variable interpolation in `PHP Source.sublime-syntax`.
- The `with_prototype` in `PHP.sublime-syntax` in order to support HTML in out of `<?php ... ?>` tag.

(Those `embed`s are fine as they barely increase the cache size, but you can't use `embed` to implement variable interpolation.)

Unfortunately, they are all language features in PHP...

Remove some heredocs may help a little bit, but the cache size still very large with a comparison to other languages.

**Comment by deathaxe** [comment]
I second all your results. I'v done the same steps with regards using PHP/JS/CSS from ST3 and commenting out all the support stuff without reasonable difference. ST4 is definitly slower even with unchanged syntax definitions. So syntax complexity is not the only nor primary reason.

I don't see such delays with JSP (part of Java Rewrite) and latest changes introduced to Rails package (PR). JSP and HAML both make huge use of embedding JS/CSS and even Ruby/Java into each other very much the same way as we do in #2789. Syntax cache of both packages is way smaller.

But I had to notice an huge impact of latest Windows 21H1. All my syntax tests and benchmark files now take 2-3 times more time than they used to do with 20H1. I first blamed ST4107, but it is the same for ST4095. 

Running the same tests on my bussiness notebook (Windows 10 1903) which normally used to be 30% slower than my private one still shows the same benchmark times with ST4107.

So some of the most recent performance drops seem to be caused by OS upgrade. I haven't activly updated drivers or something like that.

I turned off hardware accelleration to avoid performance impacts by opengl drivers for benchmarking, but finally turned out it doesn't matter much.

**Comment by deathaxe** [comment]
Finally found the initial discussion: https://forum.sublimetext.com/t/st4-high-cpu-loads-while-saving-php-files-on-win-possible-issue-in-php-package/57435/9

**Comment by deathaxe** [comment]
We can keep interpolation support in HEREDOCs using `embed`. It just means to create an intermediate inherited syntax definition for each of those the same way as we did for the others already.

- JSON (for PHP).sublime-syntax
- SQL (for PHP).sublime-syntax
- ...

The only disadvantage is the number of syntaxes increasing.

**Comment by FichteFoll** [comment]
> We can keep interpolation support in HEREDOCs using `embed`.

But do we gain anything from that? Does it reduce the cache footprint? Or are the loaded lazily?

**Comment by jfcherng** [comment]
> > We can keep interpolation support in HEREDOCs using `embed`.
> 
> But do we gain anything from that? Does it reduce the cache footprint? Or are the loaded lazily?

In my test, they are loaded lazily.

**Comment by deathaxe** [comment]
Yes we do.

First of all a `prototype:`  behaves much more sane than `with_prototype`. I never hit any inclusion loops with the former one while the latter one caused those much more easily. Somehow they behave different in that way. Furthermore `prototype` respects `meta_include_prototype` which `with_prototype` doesn't. It helps to keep things under control, too.

Another thing is `with_prototype` converting any `embed` within the syntax being pushed on stack into another `push with_withprototype`, so we loose all benefints `embed` has to offer.

By just extending the embedded syntaxes and include `interpolations` context into normal `prototype` we can work around all of it. Only disadvantage is: If those embedded syntaxes embed others, those wouldn't support interpolation without creating further intermediate syntaxes.

It is tedious but the only way out atm.

**Comment by FichteFoll** [comment]
> Yes we do.

Well, I know there are general advantages for it, but I was curious about the relevance to this issue in particular.

**Comment by jfcherng** [comment]
I do a simple "[replace `with_prototype` with `embed`](https://github.com/sublimehq/Packages/files/6551000/PHP.zip)" experiment. 

With ST 4107 clean portable, unmodified:
![Snipaste_2021-05-27_11-26-26](https://user-images.githubusercontent.com/6594915/119762542-7df39800-bee0-11eb-9829-b20b35c89c26.png)

With ST 4107 clean portable, "replace `with_prototype` with `embed`":

The size of `PHP.sublime-syntax.rcache` drops from 11MB to about 8MB.
![Snipaste_2021-05-27_11-38-42](https://user-images.githubusercontent.com/6594915/119762609-9bc0fd00-bee0-11eb-891e-385acd306336.png)
![Snipaste_2021-05-27_11-39-50](https://user-images.githubusercontent.com/6594915/119762612-9cf22a00-bee0-11eb-834e-5e3049b0e4ee.png)

It helps a little bit, but 8MB is still too large imo...

**Comment by deathaxe** [comment]
Followed that route any further https://github.com/deathaxe/sublime-packages/tree/wip/php/PHP

It's based on PR #2789

Doesn't make much of a difference.

- First load of test file after startup takes 5-6seconds.
- Indexer still hangs around for a long time as well after safing a file
- Cache size is nearly the same (48MB).

There must be something else going on.

**Comment by RishishPandey** [comment]
I am facing a hang situation since I upgraded to sublime 4 a few days back. Every time you're typing () {} [] then it hangs and takes about 40 to 60 seconds. And it usually happens with files that have a large codebase.

My current file where I experience this issue has 50K+ lines.

To confirm this issue is from PHP syntax highlighting - I turned it off and switched to text mode and noticed no lag.

**Comment by jfcherng** [comment]
> And it usually happens with files that have a large codebase.

Do you know any public codebase which suffers from that?

**Comment by RishishPandey** [comment]
> Do you know any public codebase which suffers from that? 

No - I don't.

> 50K+ line single PHP file sounds crazy (in PHP world) though... but ST should be able to deal with it.

hahaha - yes ST is able to do it - it's just PHP syntax highlighter that is causing the issue. I switched to javascript syntax and it has no such issues.

**Comment by rchl** [comment]
> it's just PHP syntax highlighter that is causing the issue

It's hard to say for sure if it's purely a syntax issue because there can be plugins/packages that rely specific syntax being enabled and trigger additional functionality. So changing the syntax can also disable that extra functionalities that might be the culprit here. Have you tried to reproduce in [safe mode](http://www.sublimetext.com/docs/safe_mode.html)?

I mean, there are clearly performance problems but waiting 20s on typing `(` and such sounds like it could be by some plugin providing completions or something.

**Comment by RishishPandey** [comment]
It's slow in Safe mode as well.

**Comment by BenjaminSchaaf** [comment]
I've narrowed down a core issue resulting in horrible loading times due to the cache being ignored, through the initial load is still incredibly slow.

**Comment by BenjaminSchaaf** [comment]
With some further investigation, the use of `with_prototype` is causing essentially all the slowdown in the initial load. The problem is that it requires making a full copy of not just the syntax being pushed, but also everything it includes/embeds, so you get none of the benefits of the lazy loading.

**Comment by BenjaminSchaaf** [comment]
Your PHP branch only results in 12MB of cache, though I wasn't able to observe much of a difference in load times on my workstation with caching disabled.

**Comment by deathaxe** [comment]
Overall cache size grows if HEREDOCs with SQL, HTML, ... syntaxes appear in PHP source to a max of about 48MB. A rcache file is created for each of the embedded files lazily as soon as one appears.

I second your observation about load times. Haven't seen much differences, too.

The question is - are such constructs effective to prevent "25000 context limit error" or is it just not worth the effort?

**Comment by jfcherng** [comment]
> Overall cache size grows if HEREDOCs with SQL, HTML, ... syntaxes appear in PHP source to a max of about 48MB.

When testing with the syntax test file, all of them gets loaded for sure. But for daily use, they most likely won't.

**Comment by shadoWalker89** [comment]
I'm facing the same issue. Sublime 3 opens file instantly but with 4 it takes a couple of seconds and even shows a progress bar.
Even when i have a scratch buffer in sublime text 4 it takes a couple of seconds to show the code

**Comment by RishishPandey** [comment]
Is there any ETA by when this issue will be resolved - it's been a hassle using sublime now because of this bug.

**Comment by jfcherng** [comment]
Please try ST 4108 if you are a license user.

**Comment by PapayaMedia** [comment]
> Try ST 4109 if you are a license user. It opens PHP files instantly on my side.

I just installed ST 4109.

The first time I executed ST, the first PHP file I opened took some seconds to open, but after that, the following ones opened almost immediately.

The second time I executed ST, even the first PHP file opened really quick.

**Comment by BenjaminSchaaf** [comment]
I'm going to close this. While there's certainly things we can do to improve the initial load time, loading from cache is plenty fast enough at this point.
