### ISSUE TITLE
[Ruby] Syntax Highlight in Monokai theme on Sublime 4

### ISSUE THREAD

**Issue by aglushkov** [sublimehq/Packages#2841]
- Sublime Version: 4
- OS Version: Ubuntu 18.04.5 LTS

Issue is only with Monokai theme -
Incorrect blue color of keywords `module`, `class`, `def`. It was red on previous sublime versions.

```ruby
module Foo
  class Bar
    def method
    end
  end
end
```

I fixed this for myself with this config (Monokai.sublime-color-scheme):
```json
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
  "variables":
  {
  },
  "globals":
  {
  },
  "rules":
  [
    {
        "name": "Storage type",
        "scope": "storage.type",
        "foreground": "var(red2)",
        "font_style": "italic"
    }
  ]
}
```

**Comment by deathaxe** [comment]
Several general purpose declaration keywords such as `module`, `class` and `def` are scoped `keyword.declaration` in all syntax definintions as of ST4 while they used to be scoped `storage.type` (in others) or `keyword.control` (in Ruby). ST provides a so called "forward fill" to tint tokens of that new scope the same way as `storage.type` because latter one was the most commonly used scope for such keywords.

Your solution directs into correct direction already. It is the color scheme which needs some tweaks to maintain "old" colors. Monokai has fallen behind with regards to recent scope changes/improvements - one reason why it is not the default color scheme any longer.

This topic has been discussed several times during the last dev cycle. The intention was to tweak Monokai, which hasn't happened until release.

That's basically an core issue as Monokai is not part of this syntax definition packages repo. BUT: As `sublime-color-scheme` files can override each other, I wonder whether we might want to add a  Ruby specific "patch" of Monokai to the Ruby package.

We already did so for thome key bindings, so it would be a logical step to also do for color scheme.

The way to go then, was to create coloring rules for `keyword.declaration`.

**Comment by aglushkov** [comment]
Thanks a lot :+1:

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in core.

**Comment by BenjaminSchaaf** [comment]
Fixed in build 4109
