### ISSUE TITLE
[Haskell] Treat `->` right arrow token depending on context

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#2868]
_Originally posted by @FichteFoll in https://github.com/sublimehq/Packages/pull/2679#discussion_r566243705_

Follow-up to #2679, where all instances of `->` are currently scoped as `keyword.operator.arrow.haskell`.

There are largely three instances of right-hand arrow usages (that I know of), none of which is an operator:

1. In a lambda definition to separate parameters from the body. In other languages, such as JavaScript, this is highlighted as `keyword.declaration.function`.
 
  ```hs
  \x -> x * 2
  ```

2. In a case-of statement to separate the pattern from the body. This isn't a normal (or assignment) operator and part of a flow control structure, so I'd use `keyword.control.conditional`. https://wiki.haskell.org/Case

  ```hs
  finishPosition pos = case pos of
    1 -> "You won Gold"
    2 -> "You won Silver"
    3 -> "You won Bronze"
    _ -> "You didn't win a medal"

  case () of _
               | cond1     -> ex1
               | cond2     -> ex2
               | cond3     -> ex3
               | otherwise -> exDefault

  {-# LANGUAGE MultiWayIf #-}
  if | guard1 -> expr1
     | ...
     | guardN -> exprN
  ```

3. In a function signature, where it functions as a ~~separator~~ binary operator.
  
  ```hs
  if' :: Bool -> a -> a -> a
  func :: (->) Int ((->) Int Int)
  ```

Notes regarding other tokens that we should consider for context-specific highlighting (in different issues, most likely):

1. `<-` behaves as an assignment operator most of the time.
1. We may also want to do something for the backslash that starts a lambda.
1. Commas are generally uses as separators, but not always for sequences (via https://github.com/sublimehq/Packages/pull/2679#discussion_r566247982)
1. `|` may be used as separators in list comprehensions, in type definitions, or for guards, where they act like a conditional `case` keyword.

**Comment by deathaxe** [comment]
Please note Haskell to be a syntax with couple of ambiguilties. It is not easy or even impossible for a static code parser to find correct escapes from contexts. As python Haskell uses indention levels to group contexts primarily or by `;` optionally. Nearly all contexts which used to use heuristics to find boundaries fail easily, need special treatment for nearly every statement/expression and heavily depend on coding style to work correctly.

While it was quite easy to scope lambda definitions "special", which I had a commit for, already, the question just is whether to add one such special case in a syntax which makes it otherwise hard to introduce such sematic distinctions without making it heavily fragile.

To learn about those arguments, just follow all the issues of different repos of Haskell syntaxes (e.g. VS Code), all primarily complaining about broken highlighting from such special casing.

The point is: Those distinctions are absent for very good reasons.

**Comment by user93702699** [comment]
> 3. In a function signature, where it functions as a separator.

That's not exactly correct. In function signatures, the `->` arrow is a binary type operator.
In other words, it is a type of kind `* -> * -> *` which is syntactically represented as an operator and therefore can be used in infix notation. The following signature

```haskell
func :: Int -> Int -> Int
```

is equivalent to

```haskell
func :: (->) Int ((->) Int Int)
```

which is, in fact, equivalent to

```haskell
type A = (->)
func :: A Int (A Int Int)
```

**Comment by user93702699** [comment]
With `TypeOperators` flag, you can even define your own type operator, like this:

```haskell
{-# LANGUAGE TypeOperators #-}

type (#) = Either

main :: IO ()
main = print x

x :: Int # Int
x = Right 1
```

**Comment by deathaxe** [comment]
Nice examples which prove a statically parsed syntax should be as generic as possible.

**Comment by FichteFoll** [comment]
> That's not exactly correct. In function signatures, the `->` arrow is a binary type operator.

Thanks, I didn't know about that. Edited OP.

**Comment by deathaxe** [comment]
I guess it being said to be an operator any discussion about context sensitive distinction is obsolete.

**Comment by FichteFoll** [comment]
As far as I can see and know, the first two use cases are still keywords and can also be detected in a syntax parser/definition if we wanted. Unless you can change those symbols with some directive as well.

That said, I totally understand and agree with this issue being of low priority.
