### ISSUE TITLE
Testing syntax definitions from the command line

### ISSUE THREAD

**Issue by duncan3dc** [sublimehq/Packages#288]
Is there any way of getting Sublime to run tests in a headless type mode?

It's currently a bit awkward to have to open every file containing tests and run `build` through the GUI. It would be easier to develop if there was a simple command line way of running a series of test files.

This would also allow pull requests to be automatically tested instead of requiring manual checks

**Comment by keith-hall** [comment]
You don't need any test files open, you can either just run the `Syntax Tests - All Syntaxes` variant, or have a `.sublime-syntax` file open and run the Syntax Tests build system and it will run all tests for that syntax.

**Comment by duncan3dc** [comment]
Where does it looks for the test files? I've just opened a `.sublime-syntax` file I'm working on, hit `Ctrl+B` and it returns _"Success: 0 assertions in 0 files passed"_

**Comment by keith-hall** [comment]
I've not done extensive testing, but for me it works when the tests and definition are in the same folder, when that folder is a subfolder of the Packages folder - be it User or a specific package folder

**Comment by keith-hall** [comment]
Although it is worth noting, that in my test files, in the header, I just include the name of the sublime-syntax file - no folder or path.

**Comment by duncan3dc** [comment]
@keith-hall Ok thanks for the pointers :+1: 

@sublimehq It'd still be nice to a command line version to assist automated testing of pull requests

**Comment by wbond** [comment]
Typically you'll be running the tests as you write them, so a command line option doesn't really add a lot. I don't know of any current plans to build a headless version of Sublime Text for things like this.

As @keith-hall mentioned, the All Syntaxes variant will run the tests for every syntax currently enabled in Sublime Text.

Syntaxes and tests must be located within a Packages subfolder, or within a .sublime-package file in the Installed Packages folder. This is because Sublime Text uses the "resource loader" that is used for all settings, plugins, key maps, etc to load the syntax and tests files.

**Comment by FichteFoll** [comment]
You could also try using this Sublimelinter plugin I wrote a while ago: https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax.

**Comment by duncan3dc** [comment]
Thanks but it's really a Continuous Integration type solution I'm looking for, so we can easily ensure any syntax changes pass all tests before merging

**Comment by FichteFoll** [comment]
Take a look at [UnitTesting](https://packagecontrol.io/packages/UnitTesting) then.

**Comment by jrappen** [comment]
It would make sense to put the information in this thread into the [README.md](https://github.com/sublimehq/packages/blob/master/README.md).
