### ISSUE TITLE
[Java] import static lowercase.class.name highlights as invalid.illegal

### ISSUE THREAD

**Issue by ratijas** [sublimehq/Packages#3161]
### What happened?

Java syntax highlighting package makes wrong assumptions about case-sensitivity of package/class names, which in reality UPPER or lowercase letters make no difference to the compiler (unlike, say, Haskell or Go).

```java
import static A.b.ced;
```

Despite a poor style and code smell, this is a perfectly legit import. But ST highlights it as a error:

![ced](https://user-images.githubusercontent.com/6737986/145583396-a9300208-bf9e-4512-85ff-be0dc2f66192.png)

![b](https://user-images.githubusercontent.com/6737986/145583589-94556755-1b26-4b10-a8d4-1d14c9e7a89f.png)

**Comment by deathaxe** [comment]
> Despite a poor style and code smell, this is a perfectly legit import.

The whole Java syntax used to scope tokens in special ways depending on case before. It's heuristics therefore rely on correct coding style as ST's static parser can't resolve the real/semantic meaning of the tokens. Otherwise syntax would look very plain as any language entity (clasess, objects, constants) is parsed case-insensitive by Java compiler.

**Comment by ratijas** [comment]
Well, in this case it's a very hard false-positive, and should be fixed
