### ISSUE TITLE
[Python] whitespace around `=` formatter in f-strings

### ISSUE THREAD

**Issue by sweettyler** [sublimehq/Packages#3216]
### What happened?

I tried some new features introduced in Python 3.8, and happened to find that, in the example (attached screenshot),  the "=" are highlighted differently, depending on if there is a blank behind it.

![_print_f_string](https://user-images.githubusercontent.com/49961658/151392567-42a4b106-a98d-41e0-9d2d-86c7f3788c56.png)

Guess there is something wrong.

In VS code "=" has the same color in both print.

![_print_f_string_vscode](https://user-images.githubusercontent.com/49961658/151393773-93996a56-807d-4e39-9baa-eba9fae4a98f.png)

**Comment by jfcherng** [comment]
Wow! I didn't even know this `=` feature. Save some typing when debugging using print.

```
>>> a = 5
>>> print(f"{a = }")
a = 5
```

That `=` behaves more like a format modifier?

**Comment by sweettyler** [comment]
@jfcherng you may find some more info: https://bugs.python.org/issue36817. There are also some official docs.

**Comment by FichteFoll** [comment]
Initially implemented in #2006. I just did some quick testing and it appears that only whitespace is allowed and preserved here. Any token before `=` would result in a syntax error and any other unexpected token after it throws an error as well because `}` is expected. That should make it fairly trivial to support.

Note that the embedded `source` scope should then not cover the whitespace that will be preserved because that will be part of the final string literally.

**Comment by sweettyler** [comment]
@deathaxe I don't find anything change after I upgrade  SUBL to version 4128.

**Comment by michaelblyons** [comment]
@sweettyler Syntax highlighting changes are not included in every ST release. The changelog will mention them if they are new. To apply the changes for now, you can follow the ReadMe instructions at the root of this repo or use something like OverrideAudit to change just the `sublime-syntax` file.

**Comment by sweettyler** [comment]
@michaelblyons Thank you! I see now.
