### ISSUE TITLE
[Python] No `Python/Console Input Widget.sublime-settings` file

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3229]
### What happened?

I replace `Packages/*.sublime-package` with files here packed up into `.sublime-package` and console syntax highlighting is gone.

After some investigations, I found that `Packages/Python/Console Input Widget.sublime-settings`, which sets Python highlighting for the console input,  can be found in downloaded ST while it's never in this repo.

I thought it's set in `Default/Console Input Widget.sublime-settings` but no, it's in Python's package.

---

I am not sure which way the staff would like to fix this.

- Set syntax in `Default/Console Input Widget.sublime-settings`  instead.
- Add `Python/Console Input Widget.sublime-settings` into this repo.

**Comment by deathaxe** [comment]
We should probably add it to Python package in this repo to line up with the shipped sublime-package.

`Python/Console Input Widget.sublime-settings` makes sure the assignment is disabled in case `Python` packages is disabled via `ignored_packages`. Otherwise ST might throw errors about the missing syntax.
