### ISSUE TITLE
[CSS] Highlight of 'rem' units after float-number

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3244]
### What happened?

here 'rem' has one stylie, which is OK
```
p {
	padding-block: 1.2rem;
}
```

but with float-number `1.`, 'rem' has another style. bad.
```
p {
	padding-block: 1.rem;
}
```

**Comment by jwortmann** [comment]
`1.` is not a valid floating point number in CSS, according to https://developer.mozilla.org/en-US/docs/Web/CSS/number.

![css](https://user-images.githubusercontent.com/6579999/155316751-2d7e8ecb-7d4c-4184-8fa2-7fad116d852f.png)

Perhaps it might work to use `1.` in web browsers because browsers are not very strict about invalid syntax, so that websites can still be rendered even if they contain invalid HTML or CSS.

But I think the current highlighting to be different from `1.2rem` is the best we can do, so that programmers can see that they made a typo / syntax error.

**Comment by rchl** [comment]
`1.rem` is not a valid syntax, even in browsers
