### ISSUE TITLE
[Regular Expressions] First character in Find bar is always meta.literal

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#332]
I'm having an odd experience with the RegExp definition, wherein this syntax test will pass:

```re
\b
# <- keyword.control.anchors

\\b
# <- constant.character.escape - keyword.control.anchors
```

But if I put those same strings into the "Find" bar, I get different results:

```re
\b
# <- meta.literal

\\b
# <- meta.literal
# ^ keyword.control.anchors
```

This is also true of other strings whose first character should be something other than `meta.literal`: (`^`, `(`, `[`).

The same thing happens for Python if I change the pushed `source.regexp.python` references to `source.regexp`<sup>1</sup>:

```py
regex = re.compile(r'\b\w{1,20}')
#                    ^^ meta.literal
```

The Find bar actually *searches* correctly, but its highlighting is broken. This only happens if it is the first character. Subsequent instances are fine.

------

<sup>1</sup> Why doesn't it use the main Regular Expressions syntax by default? I was surprised to discover that there is a Python-only RegExp syntax file that isn't as robust.

**Comment by keith-hall** [comment]
I can't get `Tools` -> `Developer` -> `Show Scope Name` working when the cursor is at the very beginning of the find bar textbox, but it works after the 1st character. How did you do it @michaelblyons ?

i.e. where `|` represents the cursor
- `|\b` - nothing
- `\|b` - works

However, I can see what you mean, it doesn't highlight `\b` the same way it highlights ` \b`...

as for different regex syntaxes, I think it is because `Regular Expressions.sublime-syntax` is specific to the find panel etc. which is one regex flavor while the Python regex flavor is quite a bit different.

**Comment by keith-hall** [comment]
I worked out how to fix it and have created a PR, thanks for reporting :)

**Comment by michaelblyons** [comment]
Thanks for your super-quick response! Also, thanks for pointing out the differences in the RegExp engines at #334. I was going to ask what was different, but that turns out to be a prime example. 👍
