### ISSUE TITLE
moving snippets to "Snippets" subdirectories

### ISSUE THREAD

**Issue by MattDMo** [sublimehq/Packages#351]
I just experienced this recently whilst playing with my test installation of Sublime using these packages here. I have a bunch of custom keymaps using `insert_snippet` to fire both custom snippets I've stored in `Packages/User`, as well as "built-in" snippets that ship with Sublime. I went to use the "wrap with tag" shortcut (**`Edit -> Tag -> Wrap Selection With Tag`**), which is mapped to `Packages/XML/long-tag.sublime-snippet`, and it didn't work, because it had been moved to <code>Packages/XML/**Snippets**/long-tag.sublime-snippet</code>. 

Yes, the fix is trivial in this case, but annoying, and users aren't necessarily going to know that the change has occurred, and even if they do it may not dawn on them that this is why their shortcuts are no longer working, as packages are wrapped up in `.sublime-package` files and most people don't frequently check their contents with PackageResourceViewer. I don't read every single email that's generated out of this repo, but from skimming I've gotten the impression that a number of default packages have been reorganized in this way, yet this discussion hasn't yet been had (that I'm aware of - if so, just point me to it).

So my questions are:

1. What is the justification for changing the organization of the default packages? Is it just to make things more organized to some devs working on the default packages, or is there an overriding plan? If it's just to make things prettier, I would argue for scrapping it altogether before 3112 is released, because it's going to cause a ton of headaches - see below. And kind of as a follow-up, is this being done for *all* default packages, or just as they get worked on, or just when somebody suggests it, or what? It seems kind of disorganized at this point.
2. Have the existing **default** shortcuts been updated in `Packages/Default/Default (XXX).sublime-keymap` to go along with these changes, so they don't break either? As it happens, Wrap Selection With Tag is the only one I found in the default Linux keymap, but I didn't search the others yet.
3. Is there some sort of plan for clearly alerting as many users and developers as possible that this change has occurred, *and* they should check their custom keymaps for breaking changes? For example, I can imagine the authors of all the `vim`-mode plugins like Vintageous (and even Vintage itself) out there will need to significantly rewrite their keymaps to adjust for this.

**Comment by wbond** [comment]
1. Generally, this was done as a cleanup since package directories were littered with `.sublime-snippet` files with all sorts of names, making it hard to find functional files such as `.tmPreferences` files (which have no preset names). It should make it easier for people to work with the default packages in this cleaned-up state.
 2. The default key bindings will be updated with the next dev build.
 3. My plan is to include the move in the release notes for 3112 and the next beta build.

I was aware of these changes breaking overrides, but I can see how some users would also have key bindings for them. I think this is the kind of stuff I'd like to get in while in dev/beta instead of making breaking changes once we are "stable."

Unfortunately almost all changes to the default packages are going to break something for someone. I've been working extensively on `.sublime-syntax` files, and in the process scope names are changing. I'm sure there are some packages that rely on certain scopes existing, but in the grand scheme of things the state of the syntaxes was kind of a mess and many were broken and slow. I've been trying to stay relatively close to existing scope names to try and reduce the amount of breakage.

A lot of work has been done, and is still to be done to get things into a decent state. Once we are there we can provide a much more consistent development story and documentation for new `.sublime-syntax` files and color schemes. Right now it is a mish-mash of random scopes, with duplicates all of the place, and horrible performance issues.

Ultimately with the default packages we want to users to be able to open Sublime Text and have their code highlighted properly, quickly and with features like the Goto Symbol and indexer working properly.

**Comment by wbond** [comment]
Dev build 3112 is out with the key bindings change and the notice in the release notes.

**Comment by jbrooksuk** [comment]
👍🏻
