### ISSUE TITLE
[JSX] Template Strings scope spams more then it should

### ISSUE THREAD

**Issue by predragnikolic** [sublimehq/Packages#3515]
### What happened?

Given the following code:
```jsx
let x = <p class={`hello ${}`}>Here is some text</p>;

let div = <div></div>

export function Index() {
  return <div>index</div>
}
```
Everithing is ok.
![image](https://user-images.githubusercontent.com/22029477/198901603-e5973a54-92e6-41e4-8c84-d674ec843d2c.png)

But as soon as I delete `}` in `{`hello ${}`}`.
Things start to look like this, which is not expected.

```jsx
let x = <p class={`hello ${`}>Here is some text</p>;

let div = <div></div>

export function Index() {
  return <div>index</div>
}
```

![image](https://user-images.githubusercontent.com/22029477/198901645-803f1b3c-57bb-41a8-a501-572247510fc2.png)

Is there a way to prevent this from bleeding to the rest of the file... ideally like GitHub handles it in the code block above?

**Comment by Thom1729** [comment]
I don't think this is a bug, because syntactically valid code is highlighted correctly. Consider e.g.:

```tsx
let x = <p class={`hello ${`}>Here is some text</p>;

let div = <div></div>

export function Index() {
  return <div>index</div>
}

// `}`} />;
```

I agree that GitHub's behavior here is better. In order to implement that, we'd have to do something like detecting EOF and backtracking. Not sure exactly how this would interact with the embedding, or if it could be done without `with_prototype`.

**Comment by predragnikolic** [comment]
Haha, I literally don't know JavaScript... I would never guessed that it is a nested template literal until you made it obvious. 🙂
