### ISSUE TITLE
[PHP] Array assignment operator => no longer highlighted

### ISSUE THREAD

**Issue by FocusriteMGreenwood** [sublimehq/Packages#3600]
### What happened?

Stable channel, build 4143

The array assignment operator => used to be highlighted the same as other assignment operators, eg =  but now it's just in the normal base text colour. 

Raising as a bug because syntactically => and = serve very similar purposes in code and should be highlighted the same.

**Comment by jfcherng** [comment]
It's now intentionally scoped as `punctuation.separator.key-value.php`.

**Comment by FocusriteMGreenwood** [comment]
Additionally the highlighting of constant definitions is now incorrect:

In

`const NAME_OF_CONSTANT` 

NAME_OF_CONSTANT is the same colour as a function name in a function definition

Whereas when it's referenced, ie by

`self::NAME_OF_CONSTANT`

NAME_OF_CONSTANT is in the correct colour for constants. previously this colour was used both in the definition and the reference. The new way is inconsistent and confusing on the eye.

**Comment by FocusriteMGreenwood** [comment]
OK so how do I modify my scheme so it looks like it used to? Highlighting colour schemes are all about how it looks, there's no other reason for them. Over the last 25 years I've ported a colour scheme from one editor to another because I have poor colour vision and the colour scheme is the difference between readable code and unreadable code. I've got so used to my scheme that anything else is just confusing. I chose Sublime because I was able to make it look how I *need* it to. Changes like this are really, really, frustrating.

**Comment by jfcherng** [comment]
> how do I modify my scheme so it looks like it used to?

From command palette, find `UI: Customize Color Scheme`.
![image](https://user-images.githubusercontent.com/6594915/205442750-47f56824-e8a0-42f0-a8ea-7e07041ecf03.png)

In the right pane, add something like

```js
        {
            "scope": "punctuation.separator.key-value", // found via Ctrl+Alt+Shift+p
            "foreground": "WHATEVER_COLOR_IT_WAS",
        },
```

And you basically repeatedly do this boring process for every color that you want to change.

> for the rest of comments

The only thing I can say is that those changes are in order to make scopes between different built-in programming languages more unified. And that change will inevitably break something, unless we don't want to move on and keep scopes in a chaos.

The key thing in my opinion is that at this moment, only the ST team can make changes to built-in color schemes. But they take no public action for whatever reason.

p.s.: I don't work for SublimeHQ. So any suggestion/complaint to me just probably won't work.
