### ISSUE TITLE
[SQL] Python broken when combined with SQL syntax. Needs upgrade to version 2.

### ISSUE THREAD

**Issue by gnat** [sublimehq/Packages#3692]
### What happened?

Temporary fix is to add `version: 2` to `SQL.sublime-syntax`

https://discord.com/channels/280102180189634562/280157083356233728/1088108314379952199

```
error parsing lexer: Packages/Python/Python.sublime-syntax: syntax inheritance does not allow for mixed versions at line 3 column 1
error parsing lexer: Packages/SQL/SQL.sublime-syntax: syntax inheritance does not allow for mixed versions at line 3 column 1
error parsing lexer: Packages/SQL/SQL.sublime-syntax: syntax inheritance does not allow for mixed versions at line 3 column 1
error parsing lexer: Packages/SQL/SQL.sublime-syntax: syntax inheritance does not allow for mixed versions at line 3 column 1
error parsing lexer: Packages/SQL/SQL.sublime-syntax: syntax inheritance does not allow for mixed versions at line 3 column 1
```

**Comment by jfcherng** [comment]
By the way, if SQL is promote to v2, then all syntaxes use SQL have to be promoted to v2 as well.

**Comment by gnat** [comment]
Understood, but these broken because they are `version: 2` already

* Python
* Markdown
* PHP

Not upgraded / Not broken:

* LaTeX
* Perl
* Rails

Might be time to flip the switch.

**Comment by jfcherng** [comment]
> PHP

> PHP/Embeddings/SQL (for PHP Interpolated).sublime-syntax
> PHP/Embeddings/SQL (for PHP).sublime-syntax

are still v1.

**Comment by keith-hall** [comment]
IIRC, there's nothing to stop embedding any version syntax from any other version, it's just inheritance (and including presumably) which wouldn't allow cross-versions. If there were problems as things stand, the syntax tests in this repo would be failing.

**Comment by gnat** [comment]
> Wait so it looks like a v2 syntax can embed v1 syntaxes?

Anyone in particular in charge of this transition that needs to be notified of the breakage? @deathaxe I'm guessing? I am a Sublime user, not a dev.

**Comment by deathaxe** [comment]
I don't see any such error messages when opening python, PHP, SQL or any other file in ST 4148 SAFE MODE. And I don't see any reason for that happening, because as keith correctly stated, restrionctions with regards to v1 and v2 syntax exist for inheritance only. `embed` is not effected by such restrictions as `push ... with_prototype` isn't.

The first error about Python may be caused by an out-dated LSP-pyright (<= v1.2.15) or any other package, which inherits ST's default python syntax, but is still v1.

SQL related error messages may be caused by SQL package from PR #3046 being checked out locally. At least Rails, Ruby and PHP are known to contain inherited versions of SQL, which are v1 on current master.

To correctly use SQL v2 you'd need to merge master into that branch and symlink all packages using it.
