### ISSUE TITLE
[TypeScript] Method calls aren't scoped when they have type arguments

### ISSUE THREAD

**Issue by frou** [sublimehq/Packages#3790]
In the following...

<img width="247" alt="Screenshot 2023-06-11 at 12 05 39" src="https://github.com/sublimehq/Packages/assets/172663/3cdee492-aaa1-4eb9-892c-5f968749c85b">

* `foo` is scoped as
  * source.ts
  * meta.function-call.js
  * variable.function.js
* `bar` is scoped as
  * source.ts
  * variable.function.js
* `baz` is scoped as
  * source.ts
  * meta.function-call.method.js
  * variable.function.js
* `qux` is scoped as
  * source.ts
  * meta.property.object.js

The issue is that the `qux` identifier should have a scope indicating that it is a method/function being called, like the others do.

(ST 4143)

**Comment by Thom1729** [comment]
(Another broken case: ``foo<bar>`baz` ``.)

Fixing this bug per se isn't hard, but the code here is kind of messy and I'm wondering how heavily to refactor it.

In principle, detecting whether a variable/property is being called is fairly complicated. Even in plain JavaScript, you would need to branch because there could be a line break between the name and the open paren. In TypeScript, this is even more difficult because function type argument syntax is both a nightmare on its own terms and also mostly undocumented.

However, I'm of the opinion that this isn't a “real” syntactic distinction, and as long as it doesn't break anything we can handle it on a best-effort basis with a kind-of-dumb lookahead. I don't mind if there are false positives or negatives in pathological cases as along as the miss is limited to the scope of a single token and doesn't impact subsequent highlighting.

The simplest way to implement this would be to just add a special case with a lookahead to the contexts that handle variables with property names. In fact, this is the main part of how we currently handle this, and those lookaheads just need a minor tweak to handle type arguments. The complication is that we actually have a bunch of surrounding code that tries to detect entire function calls — name and arguments — and give them `meta.function-call`. This behavior has been in the syntax definition since forever, and it's specified in the [Scope Naming Guidelines](https://www.sublimetext.com/docs/scope_naming.html):

> Function names, including the full path, and all parameters should receive the following scope. The name of the function or method should be `variable.function`, unless the function is scoped with `support.function`.
>
> - `meta.function-call`

I'm not a fan of this behavior. Currently we're implementing it with dumb lookaheads that will definitely fail in many complex cases, even some that aren't really pathological, but which nevertheless add a surprising amount of complexity. Implementing it correctly would be very hard and would probably have performance implications. And as a bonus, I'm pretty sure it's also actually broken in many simple cases and no one has noticed because (apparently) no one actually uses `meta.function-call` for scoping anyway. (By contrast, color schemes *do* often highlight `variable.function`, which is what this issue is about.)

So I'm wondering if anyone would mind if I just cut the Gordian knot, rip out the janky code that tries to apply `meta.function-call`, and fix all of the related bugs (including this one) while I'm in there.

**Comment by frou** [comment]
Personally I completely agree with all your positions outlined there.

**Comment by keith-hall** [comment]
`Packages/Default/Indexed Reference List.tmPreferences` currently targets `meta.function-call variable.function,
        meta.function-call support.function` selector, so Goto Reference will stop working if the `meta.function-call` scope will no longer be applied. I guess solveable by adding a new `tmPreferences` file to the JavaScript package, but worth noting that the behavior will be slightly different - it could find references which are not direct invocations of the method, if the syntax is able to detect those. But maybe that's a good thing?

**Comment by Thom1729** [comment]
We could probably do something slightly less drastic, and in e.g. `foo.bar.baz()` keep `meta.function-call` around `baz()`. Not sure exactly how this would affect Goto Reference since I use LSP.

**Comment by FichteFoll** [comment]
> We could probably do something slightly less drastic, and in e.g. `foo.bar.baz()` keep `meta.function-call` around `baz()`.

I was gonna suggest this, so this has my support for a more feasible workaround with less potentially patholigical backtracking on the function detection.

> and no one has noticed because (apparently) no one actually uses `meta.function-call` for scoping anyway.

I actually *do* use `meta.function-call` in my color scheme to use italics for the function name in function calls.
