### ISSUE TITLE
[Lua] Table keys highlight in Sublime 4

### ISSUE THREAD

**Issue by DifferentialOrange** [sublimehq/Packages#3796]
### What happened?

Lua table keys color highlight in Sublime 4 is inconsistent. It is also seems unexpected to have red colored fields for string constants (used for language keywords like `local` and `return`).

Sublime 4 (apt version 4143)
![image](https://github.com/sublimehq/Packages/assets/20455996/1269b77e-14fd-4138-b09c-6779243b283e)
Sublime 3 (apt version 3211)
![image](https://github.com/sublimehq/Packages/assets/20455996/8fa0ce44-c3dd-4908-8258-207424e83221)

I'm using a clear Sublime installations without a single plugin.

**Comment by jfcherng** [comment]
I would argue it looks better now but that doesn't matter. You can use whatever color you like with a customized color scheme. https://www.sublimetext.com/docs/color_schemes.html#customization

**Comment by FichteFoll** [comment]
> Lua table keys color highlight in Sublime 4 is inconsistent. 

It differentiates between function definitions and other fields.

> It is also seems unexpected to have red colored fields for string constants (used for language keywords like local and return).

This is an issue/choice of your color scheme. Which one are you using?

**Comment by DifferentialOrange** [comment]
> This is an issue/choice of your color scheme. Which one are you using?

Monokai both on Sublime 3 and Sublime 4

**Comment by DifferentialOrange** [comment]
> It differentiates between function definitions and other fields.

What's the motivation behind the change? Especially one not regarding function definitions.

**Comment by DifferentialOrange** [comment]
> The more thing it can differetiate, the better it is.

Well, it's rather controversial since language itself does not differentiate there two cases. But I get your point.

**Comment by DifferentialOrange** [comment]
> You can use whatever color you like with a customized color scheme. https://www.sublimetext.com/docs/color_schemes.html#customization

How one can see default color scheme settings in Sublime 3 (so I can try to migrate them to Sublime 4)?

**Comment by DifferentialOrange** [comment]
> By the way, to see the `scope` of the current cursor position, press `ctrl+alt+shift+p`.

I'm not well-experienced in customizing color schemes, but scope of these two is the same yet color is not.
![image](https://github.com/sublimehq/Packages/assets/20455996/c873ab52-dbce-48f9-abc4-9756d7abf6bf)
![image](https://github.com/sublimehq/Packages/assets/20455996/9edf61d3-5bcd-4749-8781-48a118047e21)

**Comment by jfcherng** [comment]
I believe the cursor position in your screenshot is at a space rather than `func` or `val`.

**Comment by DifferentialOrange** [comment]
> I believe the cursor position in your screenshot is at a space rather than at `f`,`u`,`n`,`c` or `v`,`a`,`l`. You don't have to select a token, only the cursor position matters.

Thank you

**Comment by FichteFoll** [comment]
> What's the motivation behind the change?

It's so that function definitions inside tables are recognized and can be index for other features such as the symbol list (ctrl+r) and goto definition (f12). Both of these rely on ST being able to determine locations in files where generally shared things (classes, structs, functions) are defined.

> Especially one not regarding function definitions.

The change is more in line with the scoping guidelines in that it marks the key of a table entry as a string, similar to how it does when getting it via `a_table["field"]` (which `a_table.field` aliases to). However, tables may also be indexed by numbers via `{ [1]: "this is a number key" }`. To make this consistent across all usages, a `meta.mapping.key` scope is added for the key section in a table definition that can be used to differentiate a string used as a value from a string used as a key, because while syntactically they are both strings, they have different semantics. 

As similar concept is applied to strings in JSON which actually use the exact same syntax for keys as strings used as values, i.e. `{"key": "value"}`, so in order to show their difference in semantics, they also differentiate between the presence of a `meta.mapping.key` and `meta.mapping.value` scope at second-to-last scope level.

Monokai has a specific rule for these keys and highlights them in red. Whether that is something you like or not is for you to determine (I don't, I find the red to be too distracting), but fortunately it is also easily customized. The current rule is as follows:
```
        {
            "name": "Tag name",
            "scope": "entity.name.tag | meta.mapping.key string.unquoted",
            "foreground": "var(red2)"
        },
```
which you could simply use for an override rule in the right-hand pane that opens when you select `UI: Customize Color Scheme` in the command palette.

**Comment by FichteFoll** [comment]
Oh, by the way, this is what it looks like in my color scheme (which is based on Tubnil):
![image](https://github.com/sublimehq/Packages/assets/931051/78c736f7-f102-44d4-8ff5-667f1f92e66f)

**Comment by deathaxe** [comment]
FWIW, Also recently discussed at https://forum.sublimetext.com/t/how-to-customize-table-colors/68483/2
