### ISSUE TITLE
[Batch File] Multiline comments

### ISSUE THREAD

**Issue by Kristinita** [sublimehq/Packages#3905]
### 1. Summary

Sublime Text “Batch File” syntax doesn’t highlight multiline comments in batch files.

### 2. Steps to reproduce

Open in the Sublime Text [**Safe Mode**](https://www.sublimetext.com/docs/safe_mode.html) this batch file:

```bat
REM Single-line comment
@REM Also single-line comment

GOTO comment
This is
multiline comment
:comment

@GOTO anothercomment
This is also
multiline comment
:anothercomment

```

#### 3.1. Current

![Sublime Text comments highlight in batch files](https://i.imgur.com/f9Ir4wH.png)

Text between `GOTO` and `@GOTO` labels isn’t highlighted as comments.

#### 3.2. Expected

![BatchCodeCheck comments highlight in batch files](https://i.imgur.com/yFHVOn7.png)

Text between `GOTO` and `@GOTO` labels highlighted as comments.

### 4. About multiline comments in batch files

I took the syntax in my example from the [**most popular answer**](https://stackoverflow.com/a/8527001/5951529) (229 likes at the time of writing this issue) to a Stack Overflow question “Commenting multiple lines in DOS batch file”.

The `COMMENTS` section of the `Batch File.sublime-syntax` file at the time of writing this issue [**refers to**](https://github.com/sublimehq/Packages/blob/1fe0b24a6e4fbd1dc49bfd08adced80474c04d65/Batch%20File/Batch%20File.sublime-syntax#L156) **<https://ss64.com/nt/rem.html>**. This SS64 site web page contains the `Multi-Line Comments` paragraph:

> One approach to adding a large multi-line block of comment test is to use plain text and a `goto` command to jump execution past the comments:
> 
> @Echo OFF
> Goto :START
> 
> Description can go here
> which can even include - | > characters
>
> :START

Thanks.

**Comment by deathaxe** [comment]
Lines followed by GOTO are ignored by batch interpreter, in case the target label follows.

They wouldn't however, if the target label appears in a prior line.

```bat
:label

cmd -arg

GOTO label

another_cmd -but -no -comment

: ... many many more statements, which are no comments

```

ST's syntax can't track, where related label definitions appear.

Even with branching to check for a label following, what would be the bailout condition?

If none was specified, ST just continues lexing with active branch after 128 lines. This results in never popping contexts being pushed on stack, which might add up with each GOTO statement not followed by a related label.

Syntactically, a multi-line comment could however be much larger than 128 lines.

**Comment by Kristinita** [comment]
**Type: Question** :question:

@deathaxe, @keith-hall, @michaelblyons, how to use multiline comments in batch files in Sublime Text?

Thanks.

**Comment by michaelblyons** [comment]
Put `REM` at the beginning of each line.

**Comment by deathaxe** [comment]
I tend to start each line with `:: `

**Comment by jfcherng** [comment]
Gramatically OP's suggestion is not comment. It's hard to judge whether it's comment in ST's syntax engine too.

**Comment by FichteFoll** [comment]
This type of "multi-line comment" is just a workaround using an implementation detail of the interpreter/parser. It is not syntactically a comment and as others have already mentioned, is isn't always semantically a comment either. If you insert a new label inbetween the goto and the label definition that is supposed to mark the end of your ignored block, you now have another way to jump into the block and it's not a comment anymore. For the sake of consistency and because of the branching restrictions of ST, it is not feasible to implement "comments" like this in a generic fashion that is required for a syntax definition included in the default Packages.

We don't mark dead code as comments in other languages either, e.g. anything after a `return` statement or contents of an `if (false) {}` block.

That said, you could of course create your own third-party syntax definition that provides this feature.
