### ISSUE TITLE
Syntax highlighting wrong for Ruby constant assignments in 3114 

### ISSUE THREAD

**Issue by nolamesa** [sublimehq/Packages#393]
It seems that the latest update broke the highlighting when assigning a Ruby constant. When using a constant things look correct but when assigning a constant (e.g. FOO = "bar") the highlighting does not work. Any ideas how to fix this?

**Comment by wbond** [comment]
Can you provide a code sample and screenshot to ensure we are fixing the right thing?

**Comment by nolamesa** [comment]
I think this bug does not affect all color schemes (checked a few and in some worked while in others not). I am using Solarized light. You can see below the affected snippet. In line 2 `FOO` used to be the same color as in line 3.
<img width="271" alt="screen shot 2016-05-13 at 7 30 37 pm" src="https://cloud.githubusercontent.com/assets/292593/15265730/7ef42944-1941-11e6-8407-72a8ff74f62e.png">

**Comment by wbond** [comment]
I checked this and it appears to be working properly.

<img width="136" alt="screen shot 2016-06-02 at 3 36 20 pm" src="https://cloud.githubusercontent.com/assets/41734/15758276/d15f58a2-28d7-11e6-8a96-0765c0679842.png">

The first `FOO` has a different color because it is the definition of the constant. It will be up to your color scheme if you want that the same color as a plain identifier. By default, class, function, constant and other definitions tend to get a special color, and are included in the Goto Symbol list.

**Comment by nolamesa** [comment]
Thanks for the reply. If anyone else has this issue, I did some digging and I found how to "fix" my issue. I had to add a color rule for `entity.name.type.constant.ruby` (added it to the same rule as `variable.other.constant.ruby`). In order to do this you would need extract the default theme into packages to edit the file. Curious though if `variable.other.constant.ruby` was always used or was introduced in the latest update.
