### ISSUE TITLE
[Python] Class name highlight

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3951]
### What happened?

Repro:
```
def aaa():
	pass

class bbb(d):
	dddd = 22+33.33
	pass
```

![py](https://github.com/sublimehq/Packages/assets/4154978/157b2575-e4ff-4faa-9984-f9c408f7901f)

why func-name has one color but class-name has another? maybe it must be analogue?

ST 4 4149 on Linux. Theme: Auto.

**Comment by jfcherng** [comment]
Colors are defined by the color scheme, rather than syntax definition. Color schemes are not maintained here, and is not open-sourced online.

You have two choices.

1. Modify the color scheme locally to whatever you are happy with.
2. Suggest ST team to use the same color (for all ST users), which is less likely to happen. But if you insist, here you go https://github.com/sublimehq/sublime_text/issues/new
