### ISSUE TITLE
[LSP-Typescript] Can't go-to-symbol on symbols (exported const variables)

### ISSUE THREAD

**Issue by FilipJakab** [sublimehq/Packages#3996]
### Expected behavior

In this code snippet I would presume that `GoTo Symbol` would list these three exports:
```typescript
// ...
export const SessionUrl = joinPaths(ServerUrl, "session")
export const LogoutUrl  = joinPaths(SessionUrl, "singout")
export const LoginUrl   = joinPaths(SessionUrl, "signin")
// ...
```

I understand that indexing every variable might be exhausting, but at least `export const` would make this usable "enough".

Perhaps a config option for enabling this?

### Actual behavior

These const variable exports are not listed. Only module's functions are listed (if available).

### Steps to reproduce

1. Create a typescript file
2. Export some constants (e.g. `export const SomeConstant = 123`)
3. Try to navigate to this export via `GoTo Symbol` command

**Comment by deathaxe** [comment]
Exported symbols are scoped `meta.binding.name` and marked for indexing via

https://github.com/sublimehq/Packages/blob/master/JavaScript/Symbol%20List%20-%20Exports.tmPreferences

Thus those are globally available via ST's built-in _Goto Symbol in Project_ or _Goto Definition_ functionality.

If the issue is about LSP package's goto symbol functionality (`lsp_symbol_definition` command), you may get support at https://github.com/sublimelsp/LSP/issues.

FWIW, both is working as expected on my end (ST4175, Win11, LSP, LSP-typescript).
