### ISSUE TITLE
[Ruby] Syntax highlighting HEREDOC

### ISSUE THREAD

**Issue by cyclotron3k** [sublimehq/Packages#430]
It's valid Ruby to include more code on the same line as the opening tag of a HEREDOC block:
![single_heredoc](https://cloud.githubusercontent.com/assets/3222878/15528000/17d2536c-2283-11e6-9480-28f1c7963c76.png)

Multiple consecutive HEREDOC blocks are also valid:
![multi_heredoc](https://cloud.githubusercontent.com/assets/3222878/15528005/1b829abc-2283-11e6-91dc-989303a218f4.png)

And it can get even more complicated:
![complex_heredoc](https://cloud.githubusercontent.com/assets/3222878/15528052/7b070982-2283-11e6-97be-ef51e3bcf785.png)

**Comment by wbond** [comment]
We should be able to handle the situation where additional code is specified on the line where the heredoc starts, however it may not be possible to handle the stacked heredocs.

**Comment by wbond** [comment]
This will be fixed by https://github.com/sublimehq/Packages/tree/ruby-clear_scopes, but that won't be merged until 3115 is released since it uses new functionality in the `.sublime-syntax` file format.

**Comment by wbond** [comment]
The primary issue was resolved with build 3116. There isn't really a way to handle the nested heredocs if they are different embedded syntaxes since they would be added and popped off of the stack in reverse order than the way Ruby would interpret them.

I don't currently foresee us being able to handle the multiple, nested, different syntax heredocs without a significant rewrite of how syntaxes work.
