### ISSUE TITLE
Remove POSIX from regex in some syntax files?

### ISSUE THREAD

**Issue by jrappen** [sublimehq/Packages#440]
@wbond, please note @r-stein 's comment at https://github.com/sublimehq/Packages/pull/370#issuecomment-222311377

> Hence `[:alpha:]` does also capture non-ascii word characters like ä, ö, ü ...

Guessing that `[:alnum:]` is also effected.

**Comment by FichteFoll** [comment]
Multiple languages support unicode identifiers just fine and usage of such is intended.

LaTeX is probably a bit special in this regard due to its legacy.

**Comment by wbond** [comment]
It is intended for posix character classes to match unicode, since the regex engine is full-unicode aware. Almost all of the syntax work that has been done in 2016 has been done taking this into account.

If you want to match just ASCII, use [character class intersections](http://www.regular-expressions.info/charclassintersect.html): `[[:ascii:]&&[:alpha:]]` or `[a-zA-Z]`.

**Comment by jrappen** [comment]
Thanks for the info.

/cc @r-stein @randy3k
