### ISSUE TITLE
[Batch File] string.unquoted scope for ECHO command

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#446]
What do people think about adding a `string.unquoted.dosbatch` scope to `ECHO`ed strings? That is, after all, what they are.

``` bat
ECHO "I'm quoted. %VAR%"
::   ^^^^^^^^^^^^^^^^^^^ string.quoted.double.dosbatch
ECHO I'm unquoted. %VAR%
::   ^^^^^^^^^^^^^^^^^^^ string.unquoted.dosbatch
```

It might get a little hairy with redirection or comments, but I think popping the string when a command terminator or comment beginning is detected should work okay.

**Comment by keith-hall** [comment]
I like this idea.

> It might get a little hairy with redirection or comments, but I think popping the string when a command terminator or comment beginning is detected should work okay.

I just did a little test in `cmd` on Windows 7:

    echo hello :: rem world > test.txt :: foobar

and the content of `test.txt` became:

    hello :: rem world  :: foobar

so I think for this example:

```bat
    echo hello :: rem world > test.txt :: foobar
    ::   ^^^^^^^^^^^^^^^^^^^ string.unquoted.dosbatch - comment
    ::                      ^ keyword.operator.redirection.dosbatch
    ::                                 ^^^^^^^^^^ - comment
```

**Comment by wbond** [comment]
As of 077c7c5dd43b58a787e49965514715917397749f from yesterday, handling of parameters passed to `echo` is already being done. It was required to properly implement the `not` tests you added @michaelblyons.

That to say, I didn't add the `string.unquoted` scope. Mostly because I didn't feel like changing more since I don't normally use the syntax and want to leave improvements to people who are going to have some good examples to play around with.

**Comment by FichteFoll** [comment]
As a not here, `>` and `&` (not 100% sure about the second but about the first) can also be escaped with `^`.
