### ISSUE TITLE
Introducing TOML syntax

### ISSUE THREAD

**Issue by stoivo** [sublimehq/Packages#453]
If I created a with TOML syntax, would it get accepted?

I would take https://github.com/Gakai/sublime_toml_highlighting and change it to .sublime_syntax and add test.

**Comment by wbond** [comment]
Not currently, no.

While I am working on getting all of the currently supported syntaxes to the point of being robust, I don't think we currently want to add any other languages to the default set except for Swift.

Partially this is because there are so many different languages, and we would have to have criteria for what would allow inclusion, plus it puts more work on the Sublime HQ team, which takes away time from working on the core of Sublime Text.

Since Package Control makes it pretty easy for users to get third-party packages, and Sublime HQ is a very small team, having interested users maintain syntaxes allows us to continue to work on things the community can't do.

**Comment by stoivo** [comment]
ok, thanks for replying.
