### ISSUE TITLE
[PHP] Same scope inside and outside <?php tag

### ISSUE THREAD

**Issue by swashata** [sublimehq/Packages#478]
I am using the latest build 3114 of Stable Channel Sublime Text 3. The issue occured, when I noticed that [emmet tab expansion isn't working in PHP files](https://github.com/sergeche/emmet-sublime/issues/623). I thought it was some issue with emmet itself.

But then checking the scope inside and outside `<?php ?>` tags, it seems both are same. Here is the output of `Ctrl+Alt+Shift+p`.

**Outside PHP Tag**
`embedding.php text.html.basic meta.embedded.block.php source.php meta.class.php meta.block.php meta.function.php meta.block.php text.html.basic`

**Inside PHP Tag**
`embedding.php text.html.basic meta.embedded.block.php source.php meta.class.php meta.block.php meta.function.php meta.block.php`

I am not sure, but I think `text.html.basic` should not turn up for inside `<?php ?>` tags.

![st3-php-scope-issue](https://cloud.githubusercontent.com/assets/1623381/16145761/ffa48a86-3497-11e6-9726-a6980729dc87.gif)

Also build 3103 used to work just fine.

**Comment by wbond** [comment]
This is fixed in the current version of the PHP package in this repo, and will be part of the next dev build. You can use it now by following instructions in the readme.

PR #467 allows for an even cleaner implementation of what has already been fixed on the master branch, but requires functionality that is only available in an unreleased version of Sublime Text.
