### ISSUE TITLE
python: open brackets detector too impatient?

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#500]
Write this.

``` Python
y = list()

def x():
    return
```

Now delete the closing bracket of `list()`. Both `def` and `return` are immediately marked as errors.
I think Sublime should perhaps not do this while the line is still being edited.

**Comment by FichteFoll** [comment]
There is no way to detect if you are "still editing a line" in syntax definitions.

There are a couple tweaks that allow incomplete statements like a bare `with` keyword, but it is impossible to detect when a function (or class) call is not closed because the user is still working on it. 


However, an argument could be made for allowing statement keywords to appear in expression scopes (such as arguments) and not highlighting something like `list(def)` as invalid. Imo the current behavior helps spotting obvious errors and unclosed parentheses and ST's auto-matching behavior of parentheses should suffice with negating that downside.

**Comment by pdknsk** [comment]
I agree, there's definitely a positive side to it. Why not mark the opening bracket as an error, rather than the rest of the document basically? It's still very noticeable.

**Comment by FichteFoll** [comment]
It's not possible to know whether an opening brace does not have a closing one unless you parse the entire file. This is comparable to the halting problem.

The syntax definition engine also does not support backtracking in this way for performance reasons.

**Comment by pdknsk** [comment]
​Hmm I still think the current warning is too aggressive basically. Also
it's not immediately clear that the missing closing bracket is the culprit.

**Comment by pdknsk** [comment]
Or perhaps too verbose, rather than aggressive.

**Comment by pdknsk** [comment]
I notice that in 3114 only the first keyword following an open bracket is affected (and less prominently), rather than the rest of the document.

**Comment by FichteFoll** [comment]
Hm, I guess we could exit a parens scope on the first keyword we find. That should reduce the amount of noise from illegally placed keywords due to a missing closing paren (or other bracket).

**Comment by pdknsk** [comment]
Some possible bugs or quirks I noticed.

This works as expected, I think.

![1](https://cloud.githubusercontent.com/assets/1097609/20531004/94a070a0-b0d5-11e6-9c5a-53c9c08c576b.png)

For some reason the reverse order is different.

![2](https://cloud.githubusercontent.com/assets/1097609/20531005/94a571e0-b0d5-11e6-9f9d-7b98df0b5836.png)

I'm not sure about this.

![3](https://cloud.githubusercontent.com/assets/1097609/20531006/94a65df8-b0d5-11e6-852a-82232e37114d.png)

**Comment by wbond** [comment]
@pdknsk I think the second example is working "properly" also. The `with` is invalid inside of `[`, and then `as` is invalid unless paired with something like `with`.

**Comment by FichteFoll** [comment]
The first is odd, because it seems to exit the scope at `with` instead of `break`. Third should break at `def` instead of `:` in the unbalanced parentheses.

I'll look into it.
