### ISSUE TITLE
[Regular Expressions] if/else conditionals marked as invalid

### ISSUE THREAD

**Issue by Kristinita** [sublimehq/Packages#517]
1. `[^a-zA-Z]`

![Not latin letters](http://i.imgur.com/bEUZrVX.png)

Different metasymbols `[` and `^` have identical scope `source.regexp keyword.control.set.regexp`. 
<br />

2.`[а-яА-ЯЁё]` 

![Ёё](http://i.imgur.com/M1kUi7T.png)

`Ёё` has to have same scope as at `А-Яа-я`, if not to specify its, some realization of regular expressions passes a Cyrillic letters `Ё` and `ё`. Range of letters of the Russian alphabet is specified in regular expressions as ` [а-яА-ЯЁё]`. For example, see [article](https://habrahabr.ru/post/123845/).
<br />
3. `(<[Aa]\s+[^>]+>\s*)?<[Ii][Mm][Gg]\s+[^>]+>(?(1)\s*</[Aa]>)`

![Question mark](http://i.imgur.com/G4se8fJ.png)

`?` highlighted how Invalid, its scope `source.regexp meta.group.regexp invalid.illegal.unexpected-quantifier.regexp `. But pattern is work, see https://regex101.com/r/rW8zR4/1 . Question mark with red invalid background found in other working regular expressions, for example:

![Question mark 2](http://i.imgur.com/CUp3eFZ.png)
<br />
4. `(?<=[href|src]=")https?:\/\/.*?(?=")`

![OR](http://i.imgur.com/oslpSnp.png)

Metasymbol `|` and literals `href` and `src` have identical scope `source.regexp meta.group.regexp`. 

Thanks.

**Comment by wbond** [comment]
For issue 1.

We treat `[` and `[^` both as keyword control since they open a set. One opens a negated set, but both sequences are considered the "opening" operator. This is because the `^` only negates a set when used right after the `[`. This is similar to the construct `(?` versus a plain `?`.

For issue 2.

The ranges use `meta.set.regexp constant.other.range.regexp` whereas the individual characters just get `meta.set.regexp`. This is as intended. It highlights when you create a range.

Issue 3.

This is a bug. We currently are not handling if/else groups.

Issue 4.

Everything inside of the `[` and `]` is scoped as `meta.set.regexp`. This is correct, as far as I understand. Perhaps you intended to write the pattern as: `(?<=(href|src)=")https?:\/\/.*?(?=")`?

**Comment by Kristinita** [comment]
1. All right, thanks.

2. `Ёё`  in regular expressions surely has to enter the range of the Russian letters. `[А-Яа-я]` [not work correct](http://subcoder.ru/%D1%80%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BA%D0%B0-%D0%B0-%D1%8F%D0%B0-%D1%8F/). Google results: <https://www.google.ru/#newwindow=1&q=%22%D0%B0-%D1%8F%D0%90-%D0%AF%D0%81%D1%91%22> . Therefore `Ёё` has to be highlighted as ranges, but not as individual characters.

3. OK, thanks.

4. My pattern is correct, it finds links in the `href` and `src` attributes:  <https://regex101.com/r/rQ7nO6/1>.

**Comment by wbond** [comment]
2. That may be the case, but `Ё` and `ё` are individual codepoints in the set you created. `А-Я` is every letter from `А` to `Я`, thus a range. 

4. You pattern words, but is also being highlighted correctly. See `(?<=[href|src]=")` will match:

 - `c="` (e.g. `src="`)
 - `f="` (e.g. `href="`)

However it will also match:

 - `|="`
 - `h="`

and any of the other characters in between `[` and `]`. You can see this explanation on the page you linked, it says: "[href|src] match a single character present in the list below".
