### ISSUE TITLE
[Scala] class/object/def/val/var now incorrectly highlighted

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#548]
They're being highlighted as types, rather than as keywords (they're keywords).

To support my case…  `def` and `class` in Scala are basically identical to the same keywords in Ruby, both in semantics and in standard usage.  The Ruby mode highlights them as `keyword.control.def` and `keyword.control.class`, respectively.

**Comment by wbond** [comment]
Ruby is probably incorrect - while it has been worked on recently, it has gotten far less attention than many other syntaxes and has had fewer reviewers.

Python and JavaScript are probably two of the better reviewed syntaxes, although there are still known issues. Those use similar keywords and are scopes according to the TextMate scope documentation, AFAIK.

**Comment by FichteFoll** [comment]
Note that I am personally undecided on this issue, but more on @djspiewak's side.

In Python, `def` and `class` *are* keywords as well, but they not only indicate a different type but also have different effects on the following block (and what goes into the parens following the identifier). To me, this is a pretty sure indicator that scoping both `def` and `class` as `storage.type` is wrong since they actually have keyword-like effects on code. `storage.type` should most likely only be used for staticly typed languages like C and Java.

The exception to this would be the `async` "keyword", which certainly should get a `storage` scope, although `storage.modifier`. Furthermore, the `global` and `nonlocal` keywords are semantically tied to referring to storage, so it makes sense for those to get a storage scope too. `storage.scope` or similar?

In JavaScript we have `var`,  `let` and `const`. I would most likely mark those as `storage.type` and give `class` and `function` a `keyword.` scope for the same reason as for Python.
