### ISSUE TITLE
[Scala] SBT Mode

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#589]
SBT is the (very!) standard Scala build tool, and it has its own configuration syntax files denoted by the `.sbt` syntax.  _Technically_, `.sbt` syntax is simply an embedded DSL within Scala, and so the Scala mode does a fairly reasonable job of correctly highlighting these files.  However, it might make sense to provide an enhanced SBT mode which provides special highlighting for the "magic" SBT syntax above and beyond the Scala mode.

Features of this would include the following:
- Indexing of setting key declarations
- Scoping of the magic operators: `:=`, `+=`, `++=`, `<<=`, `<+=`, `<++=`, `%`, `%%` and `%%%`
- Scoping of fundamental built-in scopes: `run`, `Compile`, `Test`, `Integration`
- Scoping for Ivy qualifiers in scoped strings: `test`, `run`, `compile`, etc
- Scoping for `.value` magic
- Scoping for fundamental structural declarations, such as `project`, `task`, `setting` and such
- …maybe more?

As I said, the stock Scala mode (now) does a pretty good job of highlighting `.sbt` files, so this isn't _strictly_ needed, but I've played around with this sort of thing enough locally to be able to say definitively that it is helpful.  SBT is different enough from vanilla Scala that it is generally treated as a separate language within the Scala family.

**Comment by wbond** [comment]
My initial reaction would be to have this be a third-party package available via Package Control. That way users that want enhanced features/highlighting can grab the SBT package.

I think our goal here with the default packages needs to stay limited in scope (just due to available resources), but to try and support the primary syntax of all major languages. Certainly we already are supporting a number of less-popular languages in the default packages (AppleScript, Pascal), but both Jon and I currently have agreed that the only addition we are currently looking to add is Swift.

**Comment by djspiewak** [comment]
@wbond I guess it depends on whether you view SBT as part of the Scala package (as I do), or as a separate thing entirely.  The former viewpoint would be similar to how Ant and JSP are part of the Java mode.  The latter viewpoint would be more consistent with how Makefiles and Rails are separate from the C/C++ and Ruby modes, respectively.

**Comment by djspiewak** [comment]
There doesn't seem to be a lot of interest in this.  Also, the stock Scala mode (with the changes we've made) really now does do a very good job with `.sbt` files, so I'll close this.
