### ISSUE TITLE
Lighting of php code blocks - see my theme for that

### ISSUE THREAD

**Issue by bork1991** [sublimehq/Packages#617]
See image for details:

https://i.gyazo.com/3edf19e0aefbef887230d35705bc570e.png

Am adding file contains the code with extension ".tmTheme" just open it in your sublime.
https://drive.google.com/open?id=0B2JHmf6qqVHOQzlqcUVfamdIQWs

**Comment by MattDMo** [comment]
What is your question? What are the arrows in your image for?

**Comment by bork1991** [comment]
Lol is there topic for questions? my question is "how about adding that lighting for regular sublime php package"? that improve my work speed and get me using some "smarty" templaters off.

i think that lighting is improve performance for both users

**Comment by jfcherng** [comment]
IMO, the main job for official packages here is making proper scoping. 
For coloring, it's personal taste since codes have been properly scoped.
People who want to do so can simple add the corresponding scopes in their color scheme.

![image](https://cloud.githubusercontent.com/assets/6594915/18415677/3c76d9ea-782d-11e6-8d9d-81c3f86c701b.png) ![image](https://cloud.githubusercontent.com/assets/6594915/18415678/428db9d4-782d-11e6-94ef-0b98ccb2d8c6.png)

**Comment by bork1991** [comment]
ok you may change nothing and still at same place all the whole life.

**Comment by wbond** [comment]
As @jfcherng pointed out, we are providing scope information for these tags.

Currently we aren't planning changes to the existing color schemes.

You can use the scope information provided above to customize a color scheme to your liking.

This may help you: http://docs.sublimetext.info/en/latest/reference/color_schemes.html
