### ISSUE TITLE
JavaScript highlighting changed

### ISSUE THREAD

**Issue by Krinkle** [sublimehq/Packages#63]
Something happen in the last weeks making it harder to read JavaScript properly.

Two weeks ago (installed JavaScript package from version 3a0cf88a27):
<img width="1144" alt="screen shot 2015-07-06 at 16 55 27" src="https://cloud.githubusercontent.com/assets/156867/8526685/14200976-2400-11e5-9fed-2931072a3d79.png">

Current (latest one that bundles with Sublime):
<img width="1145" alt="screen shot 2015-07-06 at 16 55 34" src="https://cloud.githubusercontent.com/assets/156867/8526686/15853b60-2400-11e5-8f69-12eb2766f212.png">

This sudden explosion of green mutilates the Monokai theme as we knew it. Due to the change being in the grammar itself, there is no longer a sufficient distinction in the symbols. Making it hard (if not impossible) for theme developers to fix this. It has to be addressed in the JavaScript syntax file.

While the explosion of method symbols (green in Monokai) seems undesirable. It is however nice that object literal colons and dot notation are now recognised as distinct grammar. Though it's odd that they are highlighted as integers (purple in Monokai) instead of operators (red in Monokai).

Atom also started to recognise colons recently, but colors them red (as one would expect). Here is Atom v1.0.0 for comparison, much more in line with the original Monokai scheme:

<img width="1171" alt="screen shot 2015-07-06 at 17 04 43" src="https://cloud.githubusercontent.com/assets/156867/8526873/37358908-2401-11e5-8c6d-473dbde17a58.png">

**Comment by Krinkle** [comment]
Here is Atom v1.0.0 for comparison:

<img width="1171" alt="screen shot 2015-07-06 at 17 04 43" src="https://cloud.githubusercontent.com/assets/156867/8526873/37358908-2401-11e5-8c6d-473dbde17a58.png">

**Comment by FichteFoll** [comment]
Highlighting the dots actually looks very nice, along with the colons in objects. I'll consider adding this for Python.

**Comment by ccampbell** [comment]
:+1: I don't like that all function calls are green.. This is actually something that the babel package and Javascript (Babble) syntax did as well, so I wonder if that was taken as part of adding ES6 support.  I haven't had a chance to dig in, but I imagine it is easily fixable by changing the default theme color for a scope.

**Comment by FichteFoll** [comment]
I just tested the JavaScript highlighting in light of SublimeTextIssues/DefaultPackages#142 and noticed that function calls are highlighted as `entity.name.function`. This is wrong! This scope is only meand for function or class *definitions*, not their usages. Refer to https://manual.macromates.com/en/language_grammars#naming_conventions.

The only related scope name, albeit not exactly correct to the conventions, would be `support.function`, which is also used by the C/C++ syntaxes. I do not really agree with that either, this scope should only be used for functions provided by the language (built-in) or frameworks.

Instead, I suggest not highlighting these functions at all, like they used to.
Alternatively, if you really want to highlight function calls, I suggest using a new (!) scope named `variable.function`, which refers to function names being bound by the user. It will look like a `variable` for most color schemes since nobody is defining this scope yet, but since the variable scope is rarely used in-content (only parameters pretty much) for most languages, I suppose this will work. For languages like PHP it would probably make sense to not highlight functions at all since variables are automatically matched from starting with `$`.

**Comment by ccampbell** [comment]
@FichteFoll awesome... I figured it was something simple... also that explains how it happened.  It was taken directly from the other package used by Babble I believe which is where I first noticed it was broken.  Hopefully we can get @jskinner to update this :smile:

**Comment by ccampbell** [comment]
@FichteFoll @aziz The fix for the function scope name works fine, but I switched to the dev build of sublime and I am noticing a lot of other JavaScript things that seem to not be highlighting correctly compared to the stable release as a result of 82b5883. Should I put together a new ticket? Also, if I were to take a stab at a pull request should it go against the javascript next/javascript babel repos or against this repository?
