### ISSUE TITLE
PHP syntax highlighting inside HTML file.

### ISSUE THREAD

**Issue by eleonorsomosot** [sublimehq/Packages#670]
very confusing php syntax highlighting within HTML file.

![image](https://cloud.githubusercontent.com/assets/13271143/19465401/7ef201fc-9536-11e6-8d8c-dffb0aae1b10.png)

**Comment by keith-hall** [comment]
what color scheme are you using? also, please can you include your code as text so we can copy and paste it.

**Comment by eleonorsomosot** [comment]
I use Facebook Material Theme/Material-Theme-Darker. but even if I use any other color scheme it is still the same.

`<?php
/*
 * This is an HTML file.
 */

echo 'Hello World';
?>

<div class="col-xs-13">
    <select id="" name="">
    <?php
        foreach ( $data as $key => $value ) {
            print '<option value="' . $value['_id'] . '" ';

            if ( isset( $_POST['proxy_id'] ) && $_POST['proxy_id'] == $value['_id'] ) {
                print ' selected ';
            };

            print '>' . $value['ip'] . '</option>';
        };
    ?>
    </select>
</div>`

**Comment by keith-hall** [comment]
It looks fine to me in build 3125. Are you sure you don't have a package overriding the default syntax definition?

![php2](https://cloud.githubusercontent.com/assets/11882719/19466970/45b098c8-9517-11e6-85bb-b52b94291933.png)

**Comment by jfcherng** [comment]
What's the syntax name on the bottom-right corner of Sublime Text?

**Comment by eleonorsomosot** [comment]
@keith-hall I'm using build 3126. what package could have possibly overrode the default syntax definition? I will also be stressing @jfcherng 's point. I guess you have tried the code on a PHP file based on the bottom-right corner of your ST. the issue is when PHP is mixed inside HTML file.

**Comment by FichteFoll** [comment]
PHP inside HTML needs to be opened as PHP.

**Comment by eleonorsomosot** [comment]
@FichteFoll I understand what you mean. last build (3114) I was on did not need PHP inside HTML be opened as PHP. so now I am wondering. :)

**Comment by jfcherng** [comment]
I cannot tell how ST decides the syntax.

- file extension first?
- `first_line_match` first?

However, if you something need to do something like writing PHP inside a HTML file, you may use a plugin to make ST always use `first_line_match` to decide the syntax.

Plugins: [AppySyntax](https://packagecontrol.io/packages/ApplySyntax), [AutoSetSyntax](https://packagecontrol.io/packages/AutoSetSyntax)

**Comment by FichteFoll** [comment]
`first_line_match` has priority.

**Comment by wbond** [comment]
> Highlighting PHP codes inside a HTML file does not make sense imo.

Correct. There are many languages that can be mixed into HTML. ERB, PHP, ASP, etc. Additionally, servers that handle those file types never presume that a file ending in `.html` will be processed by the server. Instead, they require matching on the file extension.

@eleonorsomosot I just tested your example code a few different ways using Sublime Text without any third-party packages:

 1. If the contents are pasted into a new file, the PHP syntax is automatically selected
 2. If the contents are in a file ending in `.php`, the PHP syntax is used
 3. If the contents are in a file ending in `.html`, the HTML syntax is used

Based on the explanation above, I think this is functioning as-intended. We don't want to presume `.html` means PHP, because that is incorrect in plenty of situations.

If you want your Sublime Text to treat all `.html` as PHP, then you can use the *View > Syntax > Open current extensions as...* menu and select **PHP** while you have an `.html` file open.

**Comment by eleonorsomosot** [comment]
@wbond Thank you for the clear explanation. Now I understand better. It is just that I was used to it before I updated my ST. Thanks a lot everyone.

**Comment by j-tosi** [comment]
> If you want your Sublime Text to treat all `.html` as PHP, then you can use the _View > Syntax > Open current extensions as..._ menu and select **PHP** while you have an `.html` file open.

I just tried that but PHP (along with a bunch of other languages) is grayed out. I'm on a Mac, Sublime 3.2
