### ISSUE TITLE
[LaTeX Syntax] newcolumntype in package array

### ISSUE THREAD

**Issue by RomanKarwacik** [sublimehq/Packages#685]
If I use the command `\newcolumntype{L}{>{$}l<{$}}` the highlighting is a bit off:
![newcolumntype1](https://cloud.githubusercontent.com/assets/8593000/20015718/d2b636f8-a2bc-11e6-962a-9219c6956ed0.PNG)

**Comment by Elliot2560** [comment]
I'm having the exact same issue. Went through a bunch of debugging and found out that the root of the issue was in the syntax definition. It seems that the second `$` in each of the commands is not matched because there is a hanging `{`. The same behaviour occurs with sequences like `$ { $` (granted, this is not a valid use case).

**Comment by r-stein** [comment]
It may be an idea to automatically end the math mode if we match an unescaped and unmatched `}`. This is not the perfect solution, but would help in such cases and not break the whole remaining file.

**Comment by Elliot2560** [comment]
I considered that, but I don't think you can really have unmatched delimiters unless in macros, so I don't think it's wise to exit math mode this way. LaTeX is a bit similar to C because without basically preforming preprocessing, it's impossible to perfect cover all changes on the default syntax highlighting due to macros. So I think it's more realistic to just cover the default `newcommand` and commands from popular packages, which in this case is `>{}`, `<{}`, etc., from `tabular`. Or maybe adding preprocessing utilities to LaTeXTools? :P

**Comment by FichteFoll** [comment]
The blessing and the curse of a powerful macro system in programming languages.

I should check out how Rust's macro system works just so I can understand how it does things differently.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
