### ISSUE TITLE
[Scala] Class names in annotation "paths"

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#735]
Related to #605 

Can annotation identifier "paths" contain class names (with a capital first letter)? If so, we should update https://github.com/sublimehq/Packages/blob/eaf83210967163d0ee5a41d6b9075bebaae8d4a0/Scala/Scala.sublime-syntax#L156-L163 to scope them with `support.class`.

@djspiewak @gwenzek

**Comment by djspiewak** [comment]
Scala classes can have upper- or lower-case names, though it is more strongly conventional to upper-case than in other languages (due to the way it interacts with certain type system features.  Conversely, "bare" (non-class) types or package names can also have upper-case names.

Also, the `plainid` regex in the Scala mode matches upper-case names.  It only excludes symbolic names.

I'm not sure I understand why `support.class` would be an appropriate scope for a component of the annotation.  For example:

```scala
@scala.annotation.BeanProperty
```

Why would `BeanProperty` be `support.class` as opposed to just `variable.annotation`?  What about without quantification?

```scala
@BeanProperty
```

And why would that be scoped differently from this:

```scala
@scala.annotation.tailrec
```

```scala
@tailrec
```

The definition of these two annotation is almost identical (they're both classes), but you seem to be proposing scoping them differently?

**Comment by wbond** [comment]
I am working off of the scoping we use for function calls, that is, the final identifier in a path is the only one that gets `variable.function`. Preceding identifiers may be namespaces or classes, so applying `variable.function` to them would be wrong. Similarly, it would seem "wrong" to me to apply `variable.annotation` to any classes in the annotation path. Additionally, I wouldn't want any accessors to have the scope `variable` ever.

**Comment by wbond** [comment]
Mostly, I just figured all but the final identifier in an annotation would get the same scope they would when not in an annotation.

**Comment by djspiewak** [comment]
That's fair, though I think syntactically it might look a little weird because the `@` is to the far *left* (whereas function calls have nothing to the left).  Additionally, in the original version of the proposal, the "annotation scope" (whatever it ended up being) was supposed to be applied to the `@`, overlapping the `punctuation` scope.  Is that changed now?

If it's unchanged, it will end up with this rather odd situation where `variable.annotation` starts, then stops after one character and is replaced by "normal" scoping, and then starts again for a single identifier.

**Comment by wbond** [comment]
Right now `variable.annotation` (at least in Scala) is only applied to the identifier part, not the `@`. That was my intention with my summary comment in #709.

Personally I'm not a huge fan of the single-color annotations. Things like that tend to look broken to me since they cause every bit of the syntax to run together, including class names, accessors, symbols, etc.

I've opened #737 to discuss the general topic.

**Comment by wbond** [comment]
Closing this in favor of #737
