### ISSUE TITLE
JavaScript - String formatted like a regex

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#758]
Just another script which causes wrong highlighting in JavaScript syntax (dev JavaScript sublime syntax package):

    const a = 1 / /This is regex./ / 'This should be a string, not a regex.';

Here we divide `1` with a regex and then we divide result with a string. However, the string is formatted like a regex (probably because `/ /` before it). I've tried to fix it manualy, but I am not very experienced with sublime syntax notations. Sorry about that.

You can see how it looks [here](http://i.imgur.com/WgIjDx6.png).

**Comment by wbond** [comment]
This is fixed by 26b7b4da1b0b4e4683a9100d8c756df09f666e0f.

BTW, thanks for all of the JavaScript bug reports! I grabbed your test file you had posted at https://github.com/WsDwA1022/wsdwa1022.github.io/blob/master/test/1.js and checked it with the latests changes. Aside from the fact that the nesting is so deep highlighting is lost for parts, all of the actual lexing is correct.
