### ISSUE TITLE
"Expand Selection to Word" (all instances)

### ISSUE THREAD

**Issue by stevenvachon** [sublimehq/Packages#763]
This would be useful when trying to avoid complex regular expressions.

Its shortcut could be `Cmd+Option+D` (on Mac).

**Comment by FichteFoll** [comment]
Is this not what Cmd+D already does?

Also, this is not the right repository for this.

**Comment by stevenvachon** [comment]
Cmd+D is not *all* instances, only the next.

Which repo, then?

**Comment by FichteFoll** [comment]
Oh, all instances. That would be `Ctrl+Cmd+G` for you.

`{ "keys": ["ctrl+super+g"], "command": "find_all_under" }`

Issues for the core of Sublime Text (i.e. not affecting language packages) should go [here](https://github.com/SublimeTextIssues/Core/issues), but I waited specifically for you provide more details because I was rather certain it's not actually an issue.

**Comment by stevenvachon** [comment]
Thank you. That shortcut should be added to the "Selection" menu so that it can be more easily discovered.
