### ISSUE TITLE
[Javascript] bad syntax highlighting after 'new' keyword

### ISSUE THREAD

**Issue by simonhaenisch** [sublimehq/Packages#980]
```js
(function () {
    function main() {
        const module = function () {
            function foobar() {
                foo.forEach(function (f) {
                    f.forEach(function (bar) {
                        bar.forEach(function (b) {
                            b.JobDays.forEach(function (whoot) {
                                var date = new Date(whoot);
                            });
                        });
                    });
                });
            }
        };
    }
}());
```

has wrong syntax highlighting after the `new` keyword. Only happens after this pretty deep nesting I think.

**Comment by keith-hall** [comment]
This looks okay to me on build 3131:

![js980](https://cloud.githubusercontent.com/assets/11882719/26305558/788d3a5e-3ef8-11e7-9b89-5c364dcf02b1.png)

something similar was reported here: https://github.com/sublimehq/Packages/issues/403 but fixed in 3115

are you sure you're using the default JavaScript syntax?

**Comment by simonhaenisch** [comment]
yes, I use default JavaScript syntax... just checked and it's actually because of the color scheme:

jonschlinkert/sublime-monokai-extended/issues/62
